'use strict';
// Campaign systems share the existing run, inventory and rendering owners.
const CAMP={active:false,menu:null,x:320,y:224,vx:0,vy:0,walk:0,near:null,notice:'',spawn:'fire'};
let POIS=[],restoreMode=false,dialogue=null,objectiveText='',checkpointClock=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const contract=()=>CONTRACTS.find(c=>c.id===S.exp.contract)||CONTRACTS[0];
const condition=()=>CONDITIONS.find(c=>c.id===S.exp.condition)||CONDITIONS[0];
const ench=(g,id)=>S.exp.ench[g]===id;
function addJournal(id){if(!S.exp.journal.includes(id))S.exp.journal.push(id)}
function beat(id){if(S.exp.flags[id]||!BEATS[id])return false;S.exp.flags[id]=1;addJournal(id);if(RUN?.x&&state==='run')RUN.x.discoveries.push(id);save();SND.quest();const b=BEATS[id];if(state==='run')showHint(`<b>${b[0]}</b> · ${b[1]}`,9);else CAMP.notice=b[1];return true}
function relic(id){if(S.exp.relics[id])return;S.exp.relics[id]=1;beat('relic');SND.rare(3);toast(`<b>COLLECTION</b> · ${RELICS.find(r=>r[0]===id)?.[1]||id}`);save()}
function clearInputs(){for(const k in K)K[k]=false;M.l=M.r=M.lp=false;document.querySelectorAll('#touch-controls .on').forEach(e=>e.classList.remove('on'))}
function say(who,line,choices){clearInputs();const wasPaused=dialogue?dialogue.wasPaused:paused;paused=true;dialogue={wasPaused,choices};$('storybox').innerHTML=`<div class='dialog-head'><div class='portrait'><img src='${portraitFor(who)}' alt='${esc(who)} portrait'></div><div><div class='eyebrow'>FIELD COMMUNICATION</div><h2>${esc(who)}</h2></div></div><p class='story-line'>${esc(line)}</p><div class='story-choices'>${choices.map((c,i)=>`<button data-choice='${i}' ${c.disabled?'disabled':''}>${esc(c.label)}</button>`).join('')}</div>`;showPanel('story');setTimeout(()=>$('storybox').querySelector('button:not(:disabled)')?.focus(),0)}
function closeStory(){paused=dialogue?.wasPaused||false;dialogue=null;showPanel(null);clearInputs()}
function opening(){beat('arrival');say('Old Marrow',BEATS.arrival[1],[{label:'What did the signal say?',go:()=>say('Old Marrow','“Keep the lamps lit. Don’t let them cut the roots.” Find her brass relay by the blue lamps. I owe you the truth when you return.',[{label:'I’ll bring her signal home',go:()=>{beat('briefed');S.exp.flags.briefed=1;S.exp.visited.marrow=1;S.exp.visited.board=1;S.exp.visited.lift=1;S.exp.protected.copper=1;S.exp.protected.coal=1;save();closeStory();CAMP.notice='Next: walk east to the lift. Iona’s relay is marked in blue.'}}])}])}
const hubStations=()=>PROJECTS.concat([{id:'marrow',n:'Marrow’s Tent',who:'Old Marrow',x:174,y:184},{id:'locker',n:'Safe Storage',who:'Vela',x:76,y:274},{id:'lift',n:'Descent Lift',who:'Finch',x:510,y:274},{id:'fire',n:'Campfire',who:'Joss',x:370,y:184}]).map(s=>CAMP_LAYOUT[s.id]?{...s,x:CAMP_LAYOUT[s.id][0],y:CAMP_LAYOUT[s.id][1]}:s);
function enterCamp(reason='return'){
 if(needsIntro()){beginIntro(false);return}
 CAMP.active=true;CAMP.menu=null;S.lastResult=null;state='surface';paused=false;P=null;RUN=null;S.checkpoint=null;enemies=[];items=[];projs=[];zones=[];parts=[];dyns=[];flares=[];rocks=[];dlights=[];texts=[];clearInputs();showPanel(null);$('hud').style.display='none';$('objective').style.display='none';$('touch-controls').classList.add('on');
 CAMP.x=reason==='death'?76:320;CAMP.y=reason==='death'?215:224;CAMP.vx=CAMP.vy=0;CAMP.spawn=reason;CAMP.camera=null;CAMP.facing='down';CAMP.destination=null;CAMP.route=null;MUS.set('camp',0,0);refreshCampBar();save();if(!S.exp.flags.briefed)opening();else if(reason==='death'){const lines=['Your notebook survived. We can use that.','The mine kept your haul. It did not keep you.','Breathe first. We’ll count the losses afterward.'];CAMP.notice=lines[S.stats.deaths%lines.length]}
}
function refreshCampBar(){const e=$('campbar');e.style.display=state==='surface'?'flex':'none';e.innerHTML=`<div><span class='eyebrow'>SAFE HAVEN · MARROW’S CAMP</span><strong>${nextGoal()}</strong></div><button data-exp='guide'>GUIDE <kbd>?</kbd></button><button data-exp='quick'>PLACES <kbd>C</kbd></button><button data-exp='menu' aria-label='Main menu'>MENU</button>`;updateCampGuide()}
function nextGoal(){return !S.exp.flags.extraction?'Recover Iona’s last signal':!S.boss.brood?'Rebuild the camp · follow the signal below':!S.boss.king?'Find the keeper of the frozen seal':!S.boss.sovereign?'Follow Iona into the Sunken Root':'Return for the stories you left behind'}
function hubBlocked(x,y,stations=hubStations()){if(x<20||x>620||y<48||y>338)return true;return campTreeBlocked(x,y)||CAMP_PROPS.some(p=>Math.abs(x-p.x)<p.w&&Math.abs(y-p.y)<p.h)||stations.some(s=>s.id!=='fire'&&s.id!=='board'&&Math.abs(x-s.x)<32&&y>s.y-30&&y<s.y+7)}
function updateCamp(dt){if(CAMP.menu||document.querySelector('.panel.on'))return;let mx=(K.d||K.arrowright?1:0)-(K.a||K.arrowleft?1:0),my=(K.s||K.arrowdown?1:0)-(K.w||K.arrowup?1:0),len=Math.hypot(mx,my)||1;const f=1-Math.exp(-dt*14);CAMP.vx+=(mx/len*88-CAMP.vx)*f;CAMP.vy+=(my/len*88-CAMP.vy)*f;
 const ox=CAMP.x,oy=CAMP.y,dx=CAMP.vx*dt,dy=CAMP.vy*dt;if(!hubBlocked(CAMP.x+dx,CAMP.y))CAMP.x+=dx;if(!hubBlocked(CAMP.x,CAMP.y+dy))CAMP.y+=dy;const moved=Math.hypot(CAMP.x-ox,CAMP.y-oy);CAMP.walk+=moved;CAMP.moving=moved>.015;
 let near=null,dist=35;for(const s of hubStations()){const d=Math.hypot(CAMP.x-s.x,CAMP.y-(s.y+19));if(d<dist){near=s;dist=d}}CAMP.near=near;
 const b=$('interact');b.style.display=near?'flex':'none';if(near&&b.dataset.nearby!==near.id)b.innerHTML=`${stationIcon(near.id)}<span><strong>${esc(near.n)}</strong><small>${esc(STATION_SIGNS[near.id].use)}</small></span><kbd>E</kbd>`;b.dataset.nearby=near?.id||'';updateCampGuide();
}
function npcLine(s){const trust=S.exp.trust[s.id]||0;if(S.exp.ending.length)return `${s.who}: We have a future now. What we do with it is our next promise.`;if(S.boss.king)return `${s.who}: The King was keeping the Root asleep. Iona is still below. Bring back what she knows.`;if(S.boss.brood)return `${s.who}: The ice is open. Take a flare; cold steel will not frighten a ghost.`;if(S.exp.rescues)return `${s.who}: Hal told us what you did. There is a place for him by the fire.`;if(S.stats.deaths&&CAMP.spawn==='death')return `${s.who}: Ada kept your notebook dry. We can replace tools. We cannot replace you.`;if(S.exp.flags.extraction)return `${s.who}: I heard Iona’s recording. ${trust>1?'You keep coming back. That matters.':'Marrow has some explaining to do.'}`;return `${s.who}: ${s.id==='marrow'?'Iona took my brass relay. Blue lamps mark her route.':s.id==='forge'?'Copper is easy to work. Keep four pieces for your first pick.':'Bring people home, not just ore.'}`}
function campInteract(){if(!CAMP.near)return;const s=CAMP.near;S.exp.visited[s.id]=1;const talkKey='talk_'+s.id+'_'+Object.keys(S.exp.flags).filter(k=>!k.startsWith('talk_')).length;if(!S.exp.flags[talkKey]){S.exp.flags[talkKey]=1;S.exp.trust[s.id]=Math.min(20,(S.exp.trust[s.id]||0)+1);}save();SND.ui();if(s.id==='fire'){say('Joss',CAMP.notice||'Twelve names on the missing board. One fire still burning. Rest here; then choose who you are going back for.',[{label:'Sit for a moment',go:()=>{closeStory();SND.heal()}},{label:'Read the camp sign',go:()=>{closeStory();openCamp('quick')}}]);return}openCamp(s.id)}
function openCamp(id){CAMP.menu=id;state='surface';clearInputs();$('interact').style.display='none';renderSurface()}
function closeCamp(){CAMP.menu=null;showPanel(null);clearInputs();refreshCampBar()}
function renderSurface(){if(!CAMP.active||!CAMP.menu){enterCamp(CAMP.spawn||'return');return}const id=CAMP.menu,s=hubStations().find(x=>x.id===id);let h=`<div class='row'><div><div class='eyebrow'>MARROW’S CAMP</div><h2>${esc(s?.n||({quick:'Places in camp',journal:'Field Journal',guide:'Your field guide'}[id]||'Expedition'))}</h2></div><span class='money'>$${fmt(S.money)}</span><button data-exp='close'>BACK TO CAMP</button></div>`;
 const request=REQUESTS[id];if(request)h+=`<div class='project'><b>${request.n}</b><p>${request.d}</p><p>Reward: ${request.reward}</p><button data-request='${id}' ${request.ready()&&!S.exp.flags['request_'+id]?'':'disabled'}>${S.exp.flags['request_'+id]?'THANK YOU':'REPORT BACK'}</button></div>`;if(s?.who)h+=`<p class='npc-line'>${esc(npcLine(s))}</p>`;
 const project=PROJECTS.find(p=>p.id===id);if(project&&!S.exp.projects[id])h+=`<div class='project'><b>RESTORE ${esc(project.n.toUpperCase())}</b><p>${project.benefit}</p><div class='req'>${reqHTML(project.c,project.m)}</div><button data-project='${id}' ${canPay(project.c,project.m)?'':'disabled'}>RESTORE</button></div>`;
 if(id==='guide')h+=guideHTML();else if(id==='quick')h+=quickHTML();else if(id==='forge')h+=tabForge()+(S.exp.projects.forge?enchantHTML():'');else if(id==='market'||id==='locker')h+=storageHTML()+tabMarket();else if(id==='workshop')h+=tabSupplies()+(S.exp.projects.workshop?utilityHTML():'');else if(id==='infirmary')h+=tabUpgrades();else if(id==='smelter')h+=S.exp.projects.smelter?refineHTML():'<p>Repair the furnace to begin processing. Raw ore remains useful for gear and contracts.</p>';else if(id==='marrow')h+=`<button data-exp='talk'>ASK ABOUT IONA</button>`+tabQuests();else if(id==='archive'||id==='journal')h+=journalHTML();else if(id==='gallery')h+=galleryHTML();else if(id==='training')h+=`<p>Safe target: test the damage and properties of your current equipment.</p><div class='grid'>${['pick','sword','bow'].map(g=>`<button data-test='${g}'>TEST ${g.toUpperCase()}</button>`).join('')}</div><p id='training-result'>The straw guardian waits. No ammunition is consumed.</p>`;else if(id==='garden')h+=gardenHTML();else{if(id==='map')h+=mapRoomHTML();h+=expeditionHTML();}
 h+=`<div class='camp-footer'>${S.won?"<button id='b-ngc'>NEW GAME+</button>":''}<button data-exp='close'>RETURN TO CAMP</button></div>`;$('surf').innerHTML=h;showPanel('surface');refreshCampBar();}
function quickHTML(){return `<p>Match these symbols to the signs outside. Choose <b>Show route</b> to follow a trail there. Once you visit, you can open that station from here.</p><div class='station-grid'>${hubStations().map(s=>`<article class='place-card'>${stationIcon(s.id)}<div><h3>${esc(s.n)}</h3><p>${STATION_SIGNS[s.id].use}</p><small>${s.x<230?'West':s.x>400?'East':'Central'} · ${s.y<100?'north lane':s.y>250?'south lane':'middle lane'}</small></div><div class='place-actions'><button data-route='${s.id}'>SHOW ROUTE</button>${S.exp.visited[s.id]?`<button data-station='${s.id}'>OPEN</button>`:''}</div></article>`).join('')}</div>`}
function storageHTML(){return `<h3>SAFE STORAGE</h3><p>Locked materials stay available for crafting and are excluded from every market action. New rare and refined materials are locked automatically.</p><div class='storage-grid'>${Object.keys(S.mats).filter(k=>S.mats[k]>0).map(k=>`<button data-lock='${k}' aria-pressed='${!!S.exp.protected[k]}'>${S.exp.protected[k]?'LOCKED':'SELLABLE'} · ${ITEMS[k].n} ×${S.mats[k]}</button>`).join('')}</div>`}
function refineHTML(){return `<h3>FURNACE · RAW → REFINED</h3><p>Safe: 1 output. Overheat: 2 output for double ore and $15 fuel. Purify: 1 output plus a 20 HP expedition ward, for $25.</p><div class='grid'>${RECIPES.map(r=>`<div class='card'><h3>${r.n} ×${S.mats[r.id]||0}</h3><p>${r.use}</p><div class='req'>${reqHTML(r.c)}</div>${['safe','hot','pure'].map(m=>`<button data-refine='${r.id}' data-mode='${m}' ${canPay(scaleCost(r.c,m==='hot'?2:1),m==='hot'?15:m==='pure'?25:0)?'':'disabled'}>${m==='hot'?'OVERHEAT':m==='pure'?'PURIFY':'REFINE'}</button>`).join('')}</div>`).join('')}</div>`}
function scaleCost(c,n){return Object.fromEntries(Object.entries(c).map(([k,v])=>[k,v*n]))}
function enchantHTML(){return `<h3 class='sec'>CHOOSE A BRANCH · ONE PER EQUIPMENT SLOT</h3><p>Replacing a branch costs its recipe. No permanent penalty. Branches remain when you forge a higher tier.</p>${Object.entries(ENCHANTS).map(([g,list])=>`<h3 class='sec'>${GEARN[g]}</h3><div class='grid'>${list.map(e=>`<div class='card ${ench(g,e.id)?'selected':''}'><span class='tag'>${e.tag}</span><h3>${e.n}</h3><p>${e.d}</p>${reqHTML(e.c)}<button data-enchant='${e.id}' data-gear='${g}' ${S.gear[g]>=0&&canPay(e.c)&&!ench(g,e.id)?'':'disabled'}>${ench(g,e.id)?'EQUIPPED':'ENCHANT'}</button></div>`).join('')}</div>`).join('')}`}
const UTILITIES=[{id:'bridge',n:'Bridge Kit',c:{alloy:1},d:'B: bridge the aimed chasm/sap tile within 4 tiles.'},{id:'decoy',n:'Decoy Lamp',c:{cbar:1,coal:2},d:'G: distract nearby non-boss enemies for 8 seconds.'},{id:'heat',n:'Heat Pack',c:{frostalloy:1},d:'H: ignore pressure and sap for 45 seconds.'},{id:'sapcharge',n:'Pollen Infusion',c:{pollen:1,amber:2},d:'Y: +15% strike damage for this expedition, but Root attention +30.'},{id:'recorder',n:'Memory Recorder',c:{voidalloy:1},d:'V: calm Root attention by 30 and reveal nearby sites.'}];
function utilityHTML(){return `<h3>FIELD UTILITIES</h3><div class='grid'>${UTILITIES.map(u=>`<div class='card'><h3>${u.n} ×${S.cons[u.id]||0}</h3><p>${u.d}</p>${reqHTML(u.c)}<button data-utility='${u.id}' ${canPay(u.c)&&(S.cons[u.id]||0)<5?'':'disabled'}>CRAFT</button></div>`).join('')}</div>`}
function journalHTML(){return `<p>Marrow’s trust: ${S.exp.trust.marrow||0} · Rescued: ${S.exp.rescues} · Contracts: ${S.exp.contracts}</p><h3 class='sec'>FIELD NOTES</h3>${S.exp.journal.length?S.exp.journal.map(id=>{const b=BEATS[id],l=LANDMARKS.find(l=>l.id===id);return `<article class='journal-entry'><b>${esc(b?.[0]||l?.n||id)}</b><p>${esc(b?.[1]||l?.line||'A route remembered. A reason to return.')}</p></article>`}).join(''):'<p>Your notebook is empty. Iona’s signal is waiting below.</p>'}<h3>CREATURE RESEARCH</h3>${Object.entries(S.stats.kt).map(([k,v])=>`<div class='row'><span>${esc(ENAME[k]||k)}</span><span>${v} defeated</span></div>`).join('')}<h3 class='sec'>MASTERY · CLAIM ONCE PER CHARACTER</h3>${MASTERY.map(([id,n,goal])=>{const v=masteryValue(id);return `<div class='mrow'><span class='nm'>${n}</span><span>${Math.min(goal,v)}/${goal}</span><button data-mastery='${id}' ${v>=goal&&!S.exp.mastery[id]?'':'disabled'}>${S.exp.mastery[id]?'CLAIMED':'CLAIM $300 + RELIC'}</button></div>`}).join('')}`}
function masteryValue(id){return {miner:S.stats.ores,rescuer:S.exp.rescues,scholar:Object.keys(S.exp.relics).length,hunter:S.stats.kills,builder:PROJECTS.filter(p=>S.exp.projects[p.id]).length,old:S.exp.actEscapes[0],ice:S.exp.actEscapes[1],root:S.exp.actEscapes[2],contracts:S.exp.contracts,endings:S.exp.ending.length}[id]||0}
function galleryHTML(){return `<p>Every three discoveries grant a backpack slot when the gallery is restored, up to five.</p><div class='grid'>${RELICS.map(([id,n,d])=>`<div class='card ${S.exp.relics[id]?'':'undiscovered'}'><h3>${S.exp.relics[id]?n:'Uncatalogued object'}</h3><p>${S.exp.relics[id]?d:'Listen to stories and explore the landmarks.'}</p></div>`).join('')}</div>`}
function gardenHTML(){return `<p>Research the Accord with a Recorded Relic, or learn the Sleeping Seal from the original charter. The Severing is always available.</p><button data-research='accord' ${!S.exp.flags.accord&&S.exp.projects.garden&&canPay({record:1})?'':'disabled'}>STUDY ACCORD · 1 Recorded Relic</button><button data-research='seal' ${!S.exp.flags.seal&&S.exp.relics.charter?'':'disabled'}>STUDY THE SLEEPING SEAL</button><p>Choices witnessed: ${S.exp.ending.map(endingName).join(', ')||'None'}</p>`}
function availableContracts(){if(!S.exp.flags.extraction)return [CONTRACTS[0]];let pool=CONTRACTS.filter(c=>!['relay','cold','memory','sap','silence','return','master'].includes(c.id)||(c.id==='cold'&&S.unl[1])||(['memory','sap','silence'].includes(c.id)&&S.unl[2])||(['return','master'].includes(c.id)&&S.boss.king));const start=(S.stats.runs*3)%pool.length;const chosen=Array.from({length:4},(_,i)=>pool[(start+i)%pool.length]);const current=contract();if(!chosen.includes(current)&&pool.includes(current))chosen[3]=current;return chosen}
function expeditionHTML(){const offers=availableContracts();if(!offers.some(c=>c.id===S.exp.contract))S.exp.contract=offers[0].id;const act=clamp(S.act,0,2),ua=Math.max(1,S.unl[act]||1);S.startL=clamp(S.startL,0,ua-1);
 return `<h3>EXPEDITION INTENTION</h3><div class='contract-grid'>${offers.map(c=>`<button data-contract='${c.id}' class='contract ${S.exp.contract===c.id?'sel':''}' aria-pressed='${S.exp.contract===c.id}'><b>${c.n}</b><small>${c.d}</small><span>$${c.reward} + materials · extract to claim</span></button>`).join('')}</div><h3 class='sec'>STARTING LOADOUT</h3><div>${[['surveyor','Surveyor · +45 oil, free scanner'],['warden','Warden · +30 HP, −3 pack slots'],['porter','Porter · +6 slots, −15% speed']].map(([id,n])=>`<button data-loadout='${id}' class='${S.exp.loadout===id?'sel':''}'>${n}</button>`).join('')}</div><h3 class='sec'>DESTINATION</h3><div>${ACTS.map((a,i)=>`<button data-act='${i}' ${S.unl[i]?'':'disabled'} class='${act===i?'sel':''}'>${a.name}${S.unl[i]?'':' · SEALED'}</button>`).join('')}</div><div>${ACTS[act].layers.slice(0,ua).map((l,i)=>`<button data-layer='${i}' class='${S.startL===i?'sel':''}'>${l.name}</button>`).join('')}</div>${S.exp.projects.map?`<label>Optional side destination<select id='variant-choice'><option value=''>Main expedition route</option>${VARIANTS.filter(v=>v.a===act||v.a<0).map(v=>`<option value='${v.id}' ${S.exp.variant===v.id?'selected':''}>${v.n}</option>`).join('')}</select></label>`:''}${S.exp.projects.tower||S.won?`<h3 class='sec'>CONDITIONS</h3><div>${CONDITIONS.map(c=>`<button data-condition='${c.id}' class='${S.exp.condition===c.id?'sel':''}' title='${c.d}'>${c.n}</button>`).join('')}</div><p>${condition().d}</p><label>Shareable seed <input id='seed-choice' maxlength='32' value='${esc(S.exp.seedText)}' placeholder='Leave blank for a new cave'></label><button data-exp='daily'>USE TODAY’S SIGNAL</button>`:''}<div class='row sec'><span class='dim'>${contract().kind==='return'?'Bring one Ancient Relic from storage.':`Oil: ${OILM(lv('oil'))}s before loadout bonuses · contracts remain risky until extraction.`}</span><button id='b-go' class='go'>DESCEND ↓</button></div>`}

// Seeded landmarks are connected after hazards are placed, so lakes cannot cut the mission route.
function routeCarve(x0,y0,x1,y1){let x=x0,y=y0;for(let n=0;n<MW+MH+10;n++){for(let j=0;j<2;j++){const xx=x+j;if(inB(xx,y)&&xx>0&&xx<MW-1&&y>0&&y<MH-1){const i=I(xx,y);if(![T.LIFT,T.BARRIER,T.BEDROCK].includes(tiles[i])){tiles[i]=T.AIR;decor[i]=0;flg[i]=0}}}if(x===x1&&y===y1)break;if(x!==x1)x+=Math.sign(x1-x);else y+=Math.sign(y1-y)}}
function worldExpansion(seed){const r=mulberry(seed^0x6fba34);POIS=[];
 const make=(kind,x,y,k,template,critical=false)=>{
  for(let j=-3;j<=3;j++)for(let i=-4;i<=4;i++){const X=x+i,Y=y+j;if(X<2||X>=MW-2||Y<k*LH+5||Y>=(k+1)*LH-3)continue;const q=I(X,Y);if(tiles[q]!==T.LIFT&&tiles[q]!==T.BARRIER){tiles[q]=T.AIR;decor[q]=0;flg[q]=0}}
  routeCarve(lifts[k].x,lifts[k].y+2,x,y+2);const p={id:`${k}_${POIS.length}`,kind,x:(x+.5)*TS,y:(y+.5)*TS,k,template,done:false,seen:false,critical};POIS.push(p);if(critical||['shrine','temple','ritual','memory'].includes(kind))slights.push({x:p.x,y:p.y,r:critical?2.6:1.7,c:critical?[.2,.38,.42]:ACT===2?[.4,.29,.12]:[.42,.29,.13],fl:critical?0:1});
  gEnemies=gEnemies.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)>TS*6);return p;
 };
 for(let k=0;k<NL;k++){
  if(k>0)routeCarve(lifts[k-1].x,lifts[k-1].y+2,lifts[k].x,lifts[k].y+2);
  const pool=ACT===2?LANDMARKS.slice(16):ACT===1?LANDMARKS.slice(6,16):LANDMARKS.slice(0,16);
  for(let n=0;n<(ACT===0?1:2);n++){const l=pool[Math.floor(r()*pool.length)],x=n===0?18:n===1?51:32,y=k*LH+19+n*11;make(l.id,x,y,k,l.id)}
 }
 const k=clamp(S.startL,0,NL-1),c=contract(),kind=c.kind;
 const objectKinds=['object','rescue','beacon','cache','fragile','speed','tonicless','echorescue','quiet','return','nest','shrine'];
 const goal=make(objectKinds.includes(kind)?kind:'dispatch',50,k*LH+20,k,'beacon',true);goal.contract=true;
 const sample=ITEMS[kind]?kind:kind==='full'?'copper':null;
 if(sample){const tile=TI.findIndex(t=>t.ore===sample);for(let n=0;n<c.goal+2;n++){const x=46+n%6,y=k*LH+25+Math.floor(n/6);if(tile>=0)tiles[I(x,y)]=tile;else gItems.push({id:sample,x:(x+.5)*TS,y:(y+.5)*TS})}}
 if(!S.exp.flags.extraction&&ACT===0){
  goal.kind='object';goal.template='beacon';make('shelter',24,30,0,'shelter');
  for(let n=0;n<7;n++)routeCarve(lifts[0].x,lifts[0].y+2,40+n,11);for(let n=0;n<7;n++)tiles[I(40+n,10)]=n<4?T.COPPER:T.COAL;
  tiles[I(46,20)]=T.CHEST;gItems.push({id:'oil',x:47.5*TS,y:21.5*TS});
  gEnemies=gEnemies.filter(e=>e.y>40*TS);gEnemies.push({type:'crawler',x:50.5*TS,y:16.5*TS});
 }
 if(S.exp.variant){const v=VARIANTS.find(v=>v.id===S.exp.variant&&(v.a===ACT||v.a<0));if(v){const p=make(v.event,17,k*LH+45,k,v.event);p.variant=v.id;decorateVariant(p,v);}}
 if(ACT===2){for(let i=0;i<tiles.length;i++)if(tiles[i]===T.WATER)tiles[i]=T.SAP;
  for(let j=0;j<3;j++)make('memory',j===0?28:j===1?44:36,(NL-1)*LH+(j===2?57:42),NL-1,'memorial');
  const p=make('echo',20,2*LH+31,2,'echo');p.special='marrow';make('court',51,4*LH+24,4,'court');
 }
 routeCarve(lifts[NL-1].x,lifts[NL-1].y+2,MW>>1,NL*LH-28);
 // Growth gates occupy optional alcoves only; they can always be mined open.
 if(ACT===2)for(const p of POIS.filter(p=>!p.critical&&p.k===3)){const x=Math.floor(p.x/TS)-3,y=Math.floor(p.y/TS);tiles[I(x,y)]=T.ROOT;p.gate={x,y,clock:0}}
 chunks={};
}
function runExpansion(seed){$('interact').style.top='';$('interact').style.bottom='';$('interact').style.display='none';$('objective').textContent='';CAMP.active=false;CAMP.menu=null;$('campbar').style.display='none';$('objective').style.display='block';objectiveText='';
 RUN.x={seed,contract:S.exp.contract,condition:S.exp.condition,loadout:S.exp.loadout,progress:0,object:false,tonics:0,hits:0,kills:0,ore:0,attention:0,discoveries:[],rescued:0,sites:0,boss:0,fragileBroken:false,damage:0,ability:0,heat:0,firstOre:-1,firstEnemy:-1,firstStory:-1,fullTime:0,oilOutTime:0,mining:0,uses:{},lastBeat:0};
 if(restoreMode)return;P.oil=P.moil+=S.exp.loadout==='surveyor'?45:0;P.hp=P.mhp+=S.exp.loadout==='warden'?30:0;P.cap+=S.exp.loadout==='warden'?-3:S.exp.loadout==='porter'?6:0;
 if(S.exp.projects.infirmary)P.hp=P.mhp+=20;if(S.exp.projects.map)P.oil=P.moil+=30;if(S.exp.projects.garden&&ACT===2)P.oil=P.moil+=45;
 if(ench('armor','porter'))P.cap+=8;if(S.exp.projects.gallery)P.cap+=Math.min(5,Math.floor(Object.keys(S.exp.relics).length/3));
 if(S.exp.flags.ward){P.hp=P.mhp+=20;delete S.exp.flags.ward}
 if(condition().id==='rich')P.oil=P.moil=Math.round(P.moil*.75);if(condition().id==='blackout')S.cons.flare+=5;
 if(condition().id==='migration')for(const p of POIS.slice(1,6)){const x=p.x+TS*5;if(!blocked(x,p.y,5,0))enemies.push(mkEnemy(ACT===2?'rootstalker':'crawler',x,p.y,p.k))}
 if(ACT===2&&S.exp.corruption>0){const debtSite=POIS.find(p=>p.k===RUN.start&&!p.critical);if(debtSite)eventSpawn(debtSite,'choir',Math.min(3,S.exp.corruption));hintOnce('rootdebt','The Root remembers the voices you abandoned. Extra <b>Choir sentries</b> now guard its passages.')}if(contract().kind==='return'&&(S.mats.relic||0)>0){S.mats.relic--;P.pack.push('relic')}
 if(!restoreMode){beat('descent');if(ACT===1)beat('frozen');if(ACT===2)beat('root');}
 save();
}
function progressValue(){if(!RUN?.x)return 0;const c=CONTRACTS.find(c=>c.id===RUN.x.contract),x=RUN.x;
 if(ITEMS[c.kind])return P.pack.filter(id=>id===c.kind).length;
 if(c.kind==='kills')return x.kills;if(c.kind==='map')return x.explored||0;if(c.kind==='full')return P.pack.length>=P.cap?1:0;if(c.kind==='boss')return x.boss;
 return x.progress;
}
function contractSuccess(ok){const c=CONTRACTS.find(c=>c.id===RUN.x.contract),x=RUN.x;return ok&&progressValue()>=c.goal&&!(c.kind==='fragile'&&x.fragileBroken)&&!(c.kind==='tonicless'&&x.tonics>0)&&!(c.kind==='speed'&&RUN.t>240)&&!(c.kind==='quiet'&&x.attention>=40)}
function nearPOI(){if(!P)return null;return POIS.find(p=>!p.done&&Math.hypot(p.x-P.x,p.y-P.y)<TS*2.6)}
function interactWorld(){if(state!=='run'||paused||P.dead)return;if(RUN.onLift>=0){endRun(true);return}const p=nearPOI();if(p)eventDialog(p);else if(ACT===2&&offerRootGate())return;else doScan()}
function finishPOI(p,line){p.done=true;RUN.x.sites++;if(p.contract&&RUN.x.progress!==-1)RUN.x.progress=1;const l=LANDMARKS.find(l=>l.id===p.template);addJournal(p.template);if(l&&!RUN.x.discoveries.includes(p.template))RUN.x.discoveries.push(p.template);if(mod('nomad'))P.hp=Math.min(P.mhp,P.hp+12);closeStory();showHint(line,7);packDirty=true;save()}
function fieldLoot(id,n=1){for(let i=0;i<n;i++)drop(id,P.x,P.y,true)}
function eventDialog(p){const l=LANDMARKS.find(l=>l.id===p.template)||LANDMARKS[3],v=VARIANTS.find(v=>v.id===p.variant),base=v?.d||l.line;
 const finish=(line,fn)=>()=>{if(p.done)return;fn?.();finishPOI(p,line)};
 const leave={label:'Leave it for now',go:closeStory};let choices=[];
 switch(p.kind){
 case 'object':choices=[{label:'Repair and copy · 2 carried Copper Ore + 25 oil',disabled:P.oil<25||P.pack.filter(id=>id==='copper').length<2,go:finish('Iona’s signal is safe in your notebook. Extract to bring her voice home.',()=>{P.oil-=25;for(let i=0;i<2;i++)P.pack.splice(P.pack.indexOf('copper'),1);RUN.x.object=true;RUN.x.firstStory=RUN.t;beat('object');relic('ribbon');S.exp.trust.marrow=(S.exp.trust.marrow||0)+2;})},{label:'Take the relay battery · +60 oil, disturb the nest',go:finish('The battery keeps you alive. The noise woke something nearby.',()=>{P.oil=Math.min(P.moil,P.oil+60);RUN.x.object=true;RUN.x.firstStory=RUN.t;beat('object');relic('ribbon');eventSpawn(p,'crawler',2);RUN.x.attention+=15})}];break;
 case 'rescue':case 'echorescue':case 'memory':case 'shelter':case 'memorial':choices=[{label:'Help them home · spend a tonic or 30 oil',disabled:!S.cons.tonic&&P.oil<30,go:finish('Their signal follows you. Bring it to the surface.',()=>{if(S.cons.tonic)S.cons.tonic--;else P.oil-=30;RUN.x.rescued++;relic(p.kind==='memory'||p.kind==='echorescue'?'glass':'whistle');})},{label:'Take the supplies · +40 oil, leave the voice; future Root sentries',go:finish('The room falls quiet. You carry what they left behind.',()=>{if(p.contract)RUN.x.progress=-1;P.oil=Math.min(P.moil,P.oil+40);fieldLoot(ACT===2?'amber':'iron',2);S.exp.corruption++;})}];break;
 case 'nest':case 'nursery':choices=[{label:'Destroy the nest · provoke its guardians',go:finish('The nest breaks. Its guardians are coming.',()=>{eventSpawn(p,ACT===2?'woodgolem':'crawler',3);fieldLoot(ACT===2?'rootsteel':'chitin',3);RUN.x.attention+=20;relic('tooth')})},{label:'Leave a flare · protect the young, heal 25',disabled:!S.cons.flare,go:finish('The young retreat from the light. You leave them alive.',()=>{S.cons.flare--;P.hp=Math.min(P.mhp,P.hp+25);S.exp.trust.marrow=(S.exp.trust.marrow||0)+1;if(p.contract)RUN.x.progress=-1})}];break;
 case 'shrine':case 'ritual':case 'temple':choices=[{label:'Offer 20 HP · +60 oil and a blessing',disabled:P.hp<=25,go:finish('The shrine returns your light. Your strikes are blessed for this expedition.',()=>{P.hp-=20;P.oil=Math.min(P.moil,P.oil+60);RUN.x.blessed=true;beat('shrine');relic('bell')})},{label:'Offer a flare · heal 20 HP',disabled:!S.cons.flare,go:finish('The old flame answers yours.',()=>{S.cons.flare--;P.hp=Math.min(P.mhp,P.hp+20);beat('shrine')})}];break;
 case 'beacon':case 'lift':case 'pump':choices=[{label:p.kind==='pump'?'Drain the room · −20 oil':'Repair the beacon · −20 oil',disabled:P.oil<20,go:finish('The machinery remembers its purpose. A route is open.',()=>{P.oil-=20;RUN.x.heat=45;fieldLoot('iron',3);beat('lift');if(p.kind==='pump'){for(let y=Math.floor(p.y/TS)-6;y<Math.floor(p.y/TS)+7;y++)for(let x=Math.floor(p.x/TS)-7;x<Math.floor(p.x/TS)+8;x++)if([T.WATER,T.SAP].includes(tAt(x,y))){tiles[I(x,y)]=T.AIR;redraw(x,y)}}if(v?.id==='rust'||v?.id==='whiteout'){P.oil=Math.min(P.moil,P.oil+55);eventSpawn(p,ACT?'wraith':'golem',2)}})},leave];break;
 case 'archive':case 'observatory':case 'court':case 'return':choices=[{label:p.kind==='return'?'Return the ancient relic':'Read the original record',disabled:p.kind==='return'&&!P.pack.includes('relic'),go:finish('The record names the King as a keeper, and the roots as the first inhabitants.',()=>{if(p.kind==='return')P.pack.splice(P.pack.indexOf('relic'),1);relic('charter');beat('kingEvidence');S.exp.flags.seal=true;if(ACT===2){beat('marrowMemory');relic('seed')}})},leave];break;
 case 'echo':choices=[{label:'Follow the blue echo · remember',go:finish('The memory shows a safe way back. You recover 35 oil.',()=>{P.oil=Math.min(P.moil,P.oil+35);beat('marrowMemory');relic('compass');RUN.x.attention=Math.max(0,RUN.x.attention-20)})},{label:'Follow the amber echo · seek riches',go:finish('A false memory opens its eyes.',()=>{fieldLoot(ACT===2?'sunamber':'gold',3);eventSpawn(p,ACT===2?'mimic':'stalker',2)})}];break;
 case 'garden':choices=[{label:'Harvest · samples and Root attention',go:finish('The stems close behind you.',()=>{fieldLoot(ACT===2?'pollen':'amethyst',3);RUN.x.attention+=20})},{label:'Tend the garden · spend 20 oil, gain 30 HP',disabled:P.oil<20,go:finish('For once, something grows because you were here.',()=>{P.oil-=20;P.hp=Math.min(P.mhp,P.hp+30);relic('seed')})}];break;
 case 'merchant':choices=[{label:'Trade 20 HP for two tonics · a future Root sentry',disabled:P.hp<=25,go:finish('The scavenger never asks for your name.',()=>{P.hp-=20;S.cons.tonic+=2;S.exp.corruption++})},{label:'Trade 2 ore for a rope',disabled:P.pack.length<2,go:finish('A fairer trade. The rope is sound.',()=>{P.pack.splice(0,2);S.cons.rope=Math.min(2,S.cons.rope+1)})}];break;
 case 'vein':case 'fossil':case 'gallery':choices=[{label:'Excavate carefully · −25 oil, preserve the fossil',disabled:P.oil<25,go:finish('A perfect impression of a leaf. There was a forest here.',()=>{P.oil-=25;fieldLoot('fossil');fieldLoot(v?.id==='starfall'?'starmetal':ACT===2?'memory':'gold',2);relic('fossil')})},{label:'Blast it open · dynamite, rich ore and falling rock',disabled:!S.cons.dyn,go:finish('The vein opens. The ceiling follows.',()=>{S.cons.dyn--;fieldLoot(ACT===2?'rootsteel':'gold',4);for(let i=0;i<4;i++)dropRock(P.x+(i-2)*16,P.y+16);RUN.x.attention+=20})}];break;
 default:choices=[{label:'Recover the contents',go:finish('Secure the cargo. Extract to complete the request.',()=>{if(p.kind==='fragile')RUN.x.fragile=true;fieldLoot(ACT===2?'memory':ACT===1?'frostite':'copper',3);relic('lens');if(ACT===1)relic('mask');S.cons.flare++;})},leave];
 }
 say(v?.n||l.n,p.contract?CONTRACTS.find(c=>c.id===RUN.x.contract).d+' '+base:base,choices.concat(choices.includes(leave)?[]:[leave]));
}
function eventSpawn(p,type,n){for(let i=0;i<n&&enemies.length<180;i++){let placed=false;for(const [dx,dy] of [[5+i,2],[-5-i,2],[0,5+i],[0,-5-i]]){const x=p.x+dx*TS,y=p.y+dy*TS;if(!blocked(x,y,7,0)&&Math.hypot(x-P.x,y-P.y)>55){const e=mkEnemy(type,x,y,p.k);e.al=3;e.cd=1.5;enemies.push(e);placed=true;break}}if(!placed)break}}
function updateExpansion(dt){if(!RUN?.x||state!=='run'||P.dead)return;const x=RUN.x;x.ability=Math.max(0,x.ability-dt);x.heat=Math.max(0,x.heat-dt);x.attention=clamp(x.attention-dt*.5,0,100);if(P.pack.length>=P.cap)x.fullTime+=dt;if(P.oil<=0)x.oilOutTime+=dt;
 if(S.exp.variant==='whiteout'&&ACT===1&&Math.sin(RUN.t*.22)>.4)RUN.dark=Math.max(RUN.dark,.2);if(S.exp.variant==='glass'&&ACT===1&&Math.hypot(P.vx,P.vy)>45&&tAt(P.x/TS|0,P.y/TS|0)===T.ICEFLOOR){hintOnce('glasscrack','Glass ice cracks under fast steps. Pause to find your footing.');if(Math.floor(RUN.t*2)!==x.lastCrack){x.lastCrack=Math.floor(RUN.t*2);dropRock(P.x-P.vx*.3,P.y-P.vy*.3)}}if(ACT===2&&P.pack.filter(i=>i==='amber').length>3){x.attention=clamp(x.attention+dt*1.3,0,100);hintOnce('sapweight','<b>Sap burden:</b> more than three amber samples attract leeches. Bank the haul or spend sap at a living gate.');}
 x.lastBeat+=dt;if(x.lastBeat>1){x.lastBeat=0;x.explored=0;for(let i=0;i<expl.length;i++)if(expl[i]&&!TI[tiles[i]].solid)x.explored++;if(curLayer>=2&&ACT===0)beat('flood');if(curLayer>=3&&ACT===0)beat('crystal');if(ACT===1&&curLayer>=1)beat('mycel');if(ACT===1&&curLayer===2)beat('core');
  if(enemies.some(e=>Math.hypot(e.x-P.x,e.y-P.y)<100&&!e.dead)){beat('enemy');if(x.firstEnemy<0)x.firstEnemy=RUN.t}if(enemies.some(e=>e.type==='wraith'&&Math.hypot(e.x-P.x,e.y-P.y)<100))beat('wraith');
  const c=CONTRACTS.find(c=>c.id===x.contract),progress=Math.min(c.goal,progressValue()),failed=(c.kind==='fragile'&&x.fragileBroken)||(c.kind==='tonicless'&&x.tonics)||(c.kind==='speed'&&RUN.t>240);
  const txt=`${c.n} · ${failed?'COMPROMISED':progress+'/'+c.goal}${progress>=c.goal&&!failed?' · EXTRACT TO CLAIM':''}\n${CONDITIONS.find(c=>c.id===x.condition).n} · ${ACT===2?'Root attention '+Math.round(x.attention)+'/100 · ':''}${x.ability?'Pulse '+Math.ceil(x.ability)+'s':'Z · pulse ready'}`;
  if(txt!==objectiveText){objectiveText=txt;$('objective').textContent=txt;}
 }
 for(const p of POIS){const d=Math.hypot(P.x-p.x,P.y-p.y);if(!p.seen&&d<90){p.seen=true;addJournal(p.template);showHint(`<b>${VARIANTS.find(v=>v.id===p.variant)?.n||LANDMARKS.find(l=>l.id===p.template)?.n||'Signal'}</b> · approach and press E.`,4);if(x.firstStory<0)x.firstStory=RUN.t;if(mod('nomad'))P.hp=Math.min(P.mhp,P.hp+12)}
  if(p.gate){p.gate.clock+=dt;if(p.gate.clock>25){p.gate.clock=0;const {x:tx,y:ty}=p.gate;if(tAt(tx,ty)===T.AIR&&!overlaps(P,tx,ty,10)&&!enemies.some(e=>overlaps(e,tx,ty,e.hw+4))){tiles[I(tx,ty)]=T.ROOT;redraw(tx,ty)}}}
 }
 const near=nearPOI(),b=$('interact');b.style.display=near||RUN.onLift>=0?'block':'none';b.textContent=RUN.onLift>=0?'SPACE / E · EXTRACT':near?'E · '+(near.contract?'MISSION':(LANDMARKS.find(l=>l.id===near.template)?.n||'DISCOVERY').toUpperCase()):'';
 if(near||RUN.onLift>=0)setPrompt('');if(x.attention>70&&ACT===2&&!x.warned){x.warned=true;showHint('<b>The Root is listening.</b> Rest quietly or use a Memory Recorder. More creatures will answer your noise.',7);const p={x:P.x,y:P.y,k:curLayer};eventSpawn(p,'rootstalker',2)}if(x.attention<30)x.warned=false;
 if(RUN.victoryDelay!=null){RUN.victoryDelay-=dt;if(RUN.victoryDelay<=0){delete RUN.victoryDelay;showVictory()}}
 checkpointClock+=dt;if(checkpointClock>=20){checkpointClock=0;save()}
}
function endExpansion(ok){const x=RUN.x;if(!x)return '';const c=CONTRACTS.find(c=>c.id===x.contract),success=contractSuccess(ok);let reward=0;
 if(success){reward=Math.round(c.reward*(S.exp.projects.board?1.25:1)*(mod('oath')?2:1));S.money+=reward;S.stats.earned+=reward;S.exp.contracts++;S.mats.coal=(S.mats.coal||0)+3;S.mats.copper=(S.mats.copper||0)+2;SND.quest()}else S.exp.failed++;
 if(ok){S.exp.actEscapes[ACT]++;S.exp.rescues+=x.rescued;if(x.rescued)CAMP.notice=`${x.rescued} ${ACT===2?'memories':'miners'} reached the camp. Hal is tending the fire.`;if(x.object&&!S.exp.flags.extraction){beat('extraction');S.exp.projects.archive=1;S.exp.visited.archive=1;S.money+=80;S.mats.copper=(S.mats.copper||0)+4;S.mats.coal=(S.mats.coal||0)+3;S.cons.rope=1;CAMP.notice='Iona’s voice restored the Archive. Your next expedition has four new intentions.';}}
 S.exp.telemetry.push({seconds:Math.round(RUN.t),seed:x.seed,act:ACT,depth:RUN.deep,success:ok,contract:success,ore:x.firstOre,enemy:x.firstEnemy,story:x.firstStory,full:Math.round(x.fullTime),dark:Math.round(x.oilOutTime),kills:x.kills,damage:Math.round(x.damage)});S.exp.telemetry=S.exp.telemetry.slice(-30);
 const discoveries=x.discoveries.map(id=>BEATS[id]?.[0]||LANDMARKS.find(l=>l.id===id)?.n||id);
 const grade=success&&ok?(x.damage===0?'S':'A'):ok?'B':x.sites?'C':'D';CAMP.spawn=ok?'return':'death';S.checkpoint=null;
 return `<section class='exp-result'><div class='eyebrow'>EXPEDITION ${grade} · SEED ${x.seed}</div><h3>${c.n} · ${success?'COMPLETE':ok?'INCOMPLETE':'LOST'}</h3><p>${success?`+$${reward}, +3 Coal, +2 Copper. Ready for another intention.`:progressValue()>0?'Your field observations survived. The contract cargo did not qualify for payment.':'No contract payment. Your notes, restored lifts and discoveries remain.'}</p>${!ok?`<p>Cause: ${esc(x.cause||'Cave creatures or hazards')}. Salvage is automatic; your best finds are listed below. ${P.oil<=0?'Leave before the lantern goes dark.':'A flare can make room to retreat.'}</p>`:''}<p>${discoveries.length?'Field discoveries: '+discoveries.map(esc).join(' · '):'Your route is recorded in the Map Room.'}</p><p>${ok&&x.rescued?`${x.rescued} rescued. `:''}${esc(CAMP.notice)}</p><b>Next: ${nextGoal()}</b></section>`;
}
function useAbility(){if(state!=='run'||paused||P.dead||!RUN.x||RUN.x.ability>0)return;RUN.x.ability=18;SND.scan();for(const e of enemies)if(!e.boss&&Math.hypot(e.x-P.x,e.y-P.y)<80){e.slow=4;e.al=0;e.vx=(e.x-P.x)*3;e.vy=(e.y-P.y)*3}dlights.push({x:P.x,y:P.y,r:8,c:[.3,.8,.85],life:1,max:1});RUN.x.attention=Math.max(0,RUN.x.attention-8);showHint('Lantern pulse · enemies slowed for 4 seconds.',2)}
function useUtility(id){if(state!=='run'||paused||!P||P.dead||!S.cons[id])return;let used=true;if(id==='sapcharge'){RUN.x.blessed=true;RUN.x.attention=clamp(RUN.x.attention+30,0,100);}else if(id==='bridge'){const x=Math.floor((M.x+camX0)/TS),y=Math.floor((M.y+camY0)/TS);if(Math.hypot((x+.5)*TS-P.x,(y+.5)*TS-P.y)<=TS*4&&[T.CHASM,T.SAP,T.WATER].includes(tAt(x,y))){tiles[I(x,y)]=T.AIR;decor[I(x,y)]=6;redraw(x,y)}else used=false}else if(id==='heat')RUN.x.heat=45;else if(id==='recorder'){RUN.x.attention=Math.max(0,RUN.x.attention-30);doScan()}else if(id==='decoy'){for(const e of enemies)if(!e.boss&&Math.hypot(e.x-P.x,e.y-P.y)<180)e.distract=8;flares.push({x:P.x,y:P.y,vx:0,vy:0,z:0,vz:0,life:8})}if(used){S.cons[id]--;SND.scan();save();toast(UTILITIES.find(u=>u.id===id).n+' used')}else showHint('Aim at water, sap or a chasm within four tiles.',3)}

// Checkpoints contain simulation state, never callbacks or DOM. Receipts cannot award loot twice.
function finiteTree(o,depth=0){if(depth>12)return false;if(o===null||typeof o==='boolean')return true;if(typeof o==='number')return Number.isFinite(o)&&Math.abs(o)<1e13;if(typeof o==='string')return o.length<200;if(Array.isArray(o))return o.length<=MW*LH*5&&o.every(v=>finiteTree(v,depth+1));if(plain(o))return Object.entries(o).every(([k,v])=>!['__proto__','constructor','prototype'].includes(k)&&finiteTree(v,depth+1));return false}
function validCheckpoint(c){if(!plain(c)||c.version!==1||!finiteTree(c))return false;const a=c.run?.a;if(!Number.isInteger(a)||!ACTS[a]||!c.run.x||!Number.isInteger(c.run.start)||c.run.start<0||c.run.start>=ACTS[a].layers.length)return false;
 const n=MW*LH*ACTS[a].layers.length;for(const k of ['tiles','dmg','decor','flg','expl'])if(!Array.isArray(c[k])||c[k].length!==n)return false;
 if(!c.tiles.every(t=>Number.isInteger(t)&&TI[t]))return false;
 if(!plain(c.player)||!Array.isArray(c.player.pack)||!c.player.pack.every(id=>ITEMS[id]&&!ITEMS[id].use)||c.player.pack.length>100)return false;
 for(const k of ['x','y','hp','mhp','oil','moil','cap','vx','vy','kx','ky','aim','cd','bcd','sw','inv','walk','step','scanCD','slot'])if(!Number.isFinite(c.player[k]))return false;
 if(c.player.x<16||c.player.x>MW*TS-16||c.player.y<16||c.player.y>LH*ACTS[a].layers.length*TS-16||c.player.mhp<=0||c.player.moil<=0||c.player.cap<1||c.player.cap>100||c.player.slot<0||c.player.slot>5)return false;
 if(!Array.isArray(c.enemies)||c.enemies.length>200||!c.enemies.every(e=>EB[e.type]&&['x','y','hp','mhp','hw','spd','dmg','t','cd','cd2','acd','an','al','vx','vy'].every(k=>Number.isFinite(e[k]))))return false;
 if(!Array.isArray(c.items)||c.items.length>1000||!c.items.every(o=>ITEMS[o.id]&&['x','y','z','vx','vy','vz','t'].every(k=>Number.isFinite(o[k]))))return false;
 if(!Array.isArray(c.pois)||c.pois.length>100||!c.pois.every(p=>typeof p.kind==='string'&&Number.isFinite(p.x)&&Number.isFinite(p.y)))return false;
 for(const k of ['zones','rocks','dyns','flares','projs','vents'])if(!Array.isArray(c[k])||c[k].length>500)return false;
 return CONTRACTS.some(q=>q.id===c.run.x.contract)&&Array.isArray(c.run.act)&&c.run.act.every(k=>Number.isInteger(k)&&k>=0&&k<ACTS[a].layers.length)&&Array.isArray(c.run.x.discoveries)&&Number.isFinite(c.run.t)&&Number.isFinite(c.run.x.seed);
}
function captureCheckpoint(){if(restoreMode||state!=='run'||!RUN?.x||!P)return;const player={...P},run={...RUN,act:[...RUN.act]};S.checkpoint={version:1,player,run,tiles:Array.from(tiles),dmg:Array.from(dmg),decor:Array.from(decor),flg:Array.from(flg),expl:Array.from(expl),enemies:enemies.map(e=>({...e})),items:items.map(o=>({...o})),pois:POIS.map(p=>({...p})),zones:zones.map(o=>({...o})),rocks:rocks.map(o=>({...o})),dyns:dyns.map(o=>({...o})),flares:flares.map(o=>({...o})),projs:projs.map(p=>({...p,hit:p.hit?[...p.hit].map(e=>enemies.indexOf(e)).filter(i=>i>=0):[]})),vents:vents.map(o=>({...o}))};}
function resumeExpedition(){const c=S.checkpoint;if(!validCheckpoint(c)){S.checkpoint=null;enterCamp();return}restoreMode=true;const seedText=S.exp.seedText;S.exp.seedText=String(c.run.x.seed);const act=S.act,start=S.startL;S.act=c.run.a;S.startL=c.run.start;startRun(c.run.a,c.run.start);S.act=act;S.startL=start;
 P=c.player;RUN={...c.run,act:new Set(c.run.act)};tiles.set(c.tiles);dmg.set(c.dmg);decor.set(c.decor);flg.set(c.flg);expl.set(c.expl);enemies=c.enemies;items=c.items;POIS=c.pois;zones=c.zones;rocks=c.rocks;dyns=c.dyns;flares=c.flares;vents=c.vents;projs=c.projs.map(p=>({...p,hit:new Set(p.hit.map(i=>enemies[i]).filter(Boolean))}));boss=enemies.find(e=>e.boss&&!e.dead)||null;chunks={};cam.x=P.x;cam.y=P.y;curLayer=layerOf(Math.floor(P.y/TS));for(let y=0;y<MH;y++)for(let x=0;x<MW;x++)if(expl[I(x,y)])miniTile(x,y);restoreMode=false;S.exp.seedText=seedText;packDirty=hotDirty=true;paused=true;if(P.dead){paused=false;endRun(false);return}if(RUN.pendingEnding){rootChoice();return}showPanel('pause');msg('EXPEDITION RESTORED · PAUSED',4);
}
function seedForRun(){const s=S.exp.seedText;if(!s)return(Math.random()*2e9)|0;if(/^\d+$/.test(s))return Number(s)>>>0;let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}

// Additional enemy roles use the same collision and damage pipeline as the original roster.
Object.assign(EB,{
 rootstalker:{hp:20,dmg:18,spd:52,hw:6},leech:{hp:12,dmg:10,spd:55,hw:4},memoryhusk:{hp:24,dmg:18,spd:42,hw:5},pollenwitch:{hp:22,dmg:16,spd:26,hw:6},woodgolem:{hp:65,dmg:25,spd:19,hw:8,armor:1},mimic:{hp:23,dmg:23,spd:70,hw:5},rootbat:{hp:13,dmg:12,spd:60,hw:4,fly:1},ambershell:{hp:30,dmg:20,spd:36,hw:7,armor:1},choir:{hp:30,dmg:12,spd:0,hw:7},foreman:{hp:160,dmg:26,spd:30,hw:9,armor:1},sovereign:{hp:1600,dmg:30,spd:12,hw:21,boss:1}
});
Object.assign(ENAME,{rootstalker:'ROOT STALKER',leech:'SAP LEECH',memoryhusk:'MEMORY HUSK',pollenwitch:'POLLEN WITCH',woodgolem:'HEARTWOOD GOLEM',mimic:'MIMIC MINER',rootbat:'ROOTBOUND BAT',ambershell:'AMBER SHELL',choir:'THE ROOT CHOIR',foreman:'THE FORGOTTEN FOREMAN',sovereign:'THE ROOT SOVEREIGN'});
const ROOT_TYPES=new Set(['rootstalker','leech','memoryhusk','pollenwitch','woodgolem','mimic','rootbat','ambershell','choir','foreman','sovereign']);
function specialEnemy(e,dt){if(!ROOT_TYPES.has(e.type))return false;if(e.type==='sovereign'){sovereignAI(e,dt);return true}const dx=P.x-e.x,dy=P.y-e.y,d=Math.hypot(dx,dy)||1;if(d>440)return true;e.cd-=dt;e.t-=dt;e.fl-=dt;e.slow=Math.max(0,e.slow-dt);e.an+=dt;e.acd-=dt;const vis=d<170&&los(Math.floor(e.x/TS),Math.floor(e.y/TS),Math.floor(P.x/TS),Math.floor(P.y/TS)),flare=nearFlare(e);let speed=e.spd*(e.slow>0?.45:1),go=vis||e.al>0||RUN.x.attention>60;
 if(e.type==='rootstalker'){const angle=Math.atan2(e.y-P.y,e.x-P.x),looking=Math.abs(Math.atan2(Math.sin(angle-P.aim),Math.cos(angle-P.aim)))<.8;if(looking||flare){go=false;e.alpha=.65}else e.alpha=1;hintOnce('rootstalker','<b>Root Stalkers</b> freeze in your gaze. Face them or lay a flare, then retreat.')}
 if(e.type==='ambershell'&&!e.awake){if(e.heard===undefined)e.heard=RUN.x.mining;if(RUN.x.mining>e.heard){e.awake=true;e.armor=false;e.t=1;SND.gwind(e.x)}else{go=false}}
 if(e.type==='mimic'&&!e.awake){go=false;if(d<64){e.awake=true;e.t=1.2;e.st='wind';SND.wraith(e.x);showHint('The amber silhouette has no lamp. <b>Mimic!</b>',3)}}
 if(e.type==='leech'&&P.pack.includes('amber')&&d<18&&e.cd<=0){P.pack.splice(P.pack.indexOf('amber'),1);e.stolen=(e.stolen||0)+1;e.flee=5;e.cd=3;packDirty=true;text(e.x,e.y-12,'SAP STOLEN',[255,190,80],0)}
 if(e.flee>0){e.flee-=dt;moveBox(e,-dx/d*speed*dt,-dy/d*speed*dt,e.hw,0);go=false}
 if(e.type==='woodgolem'){if(!e.anchor){e.anchor={x:e.x-20,y:e.y};}const tx=Math.floor(e.anchor.x/TS),ty=Math.floor(e.anchor.y/TS);if(!e.anchorCut){if(flare||tAt(tx,ty)===T.AIR&&d<48&&P.sw>0){e.anchorCut=true;e.armor=false;text(e.x,e.y-20,'ANCHOR SEVERED',[150,230,175],0)}else e.hp=Math.min(e.mhp,e.hp+dt*6)}}
 if(e.type==='choir'){go=false;if(flare)e.slow=2;else if(e.cd<=0&&vis){e.cd=5;SND.wraith(e.x);for(const q of enemies)if(q!==e&&!q.boss&&Math.hypot(q.x-e.x,q.y-e.y)<130){q.hp=Math.min(q.mhp,q.hp+4);q.al=6}zones.push({x:P.x,y:P.y,r:28,t:0,T:1.6,dmg:e.dmg})}}
 if(e.type==='pollenwitch'&&d<70&&!flare){RUN.dark=Math.max(RUN.dark,.2);hintOnce('witch','<b>Pollen Witch:</b> nearby spores dim your lamp. A flare clears the air.')}if(e.type==='pollenwitch'||e.type==='foreman'){go=vis&&d>95;if(vis&&e.cd<=0){e.cd=e.type==='foreman'?3:4;e.st='wind';e.t=1;zones.push({x:P.x+P.vx*.2,y:P.y+P.vy*.2,r:e.type==='foreman'?36:30,t:0,T:1.3,dmg:e.dmg});SND.gwind(e.x)}}
 if(e.type==='rootbat'&&vis&&e.cd<=0){e.cd=4;zones.push({x:P.x,y:P.y,r:22,t:0,T:1.2,dmg:e.dmg});SND.bat(e.x);go=false}
 if(e.type==='memoryhusk'&&!e.memoryForm)e.memoryForm=(S.stats.kt.spitter||0)>(S.stats.kt.crawler||0)?'spitter':'crawler';if(e.type==='memoryhusk'&&vis&&e.cd<=0){e.cd=3;e.st='wind';e.t=.8;e.cx=dx/d;e.cy=dy/d;SND.chit(e.x)}
 if(e.st==='wind'){go=false;if(e.t<=0){if(e.type==='memoryhusk'&&e.memoryForm==='spitter'){eshoot(e.x,e.y,Math.atan2(dy,dx),140,e.dmg,'glob');e.st='rec';e.t=1;SND.spit(e.x)}else{e.st='charge';e.t=.5;e.cx=dx/d;e.cy=dy/d}}}
 else if(e.st==='charge'){moveBox(e,e.cx*speed*3*dt,e.cy*speed*3*dt,e.hw,0);go=false;if(e.t<=0){e.st='rec';e.t=.8}}
 else if(e.st==='rec'){go=false;if(e.t<=0)e.st='idle'}
 if(flare&&['rootbat','mimic','leech'].includes(e.type)){moveBox(e,-dx/d*speed*dt,-dy/d*speed*dt,e.hw,0);go=false}
 if(go&&!P.dead&&e.t<=0){e.vx=dx/d*speed;e.vy=dy/d*speed;moveBox(e,e.vx*dt,e.vy*dt,e.hw,e.fly?2:0)}
 if(!P.dead&&d<e.hw+7&&e.acd<=0&&e.st!=='wind'&&e.st!=='rec'){e.acd=1;hurtPlayer(e.dmg,dx/d,dy/d)}return true;
}
function sovereignAI(e,dt){const d=Math.hypot(P.x-e.x,P.y-e.y);e.an+=dt;e.fl-=dt;if(e.st==='sleep'){if(d<175){e.st='listen';e.cd=3;e.ph=1;beat('sovereign');SND.roar();msg('THE ROOT SOVEREIGN · LISTENING',5)}return}if(P.dead)return;
 const ph=e.hp/e.mhp>.68?1:e.hp/e.mhp>.34?2:3;if(ph!==e.ph){e.ph=ph;e.cd=3;SND.roar();msg(ph===2?'THE FLOOD RISES · SAVE THE BLUE MEMORIES':'THE ROOT REMEMBERS YOUR FOOTSTEPS',5);
  if(ph===2){for(let y=Math.floor(e.y/TS)-8;y<=Math.floor(e.y/TS)+8;y++)for(let x=Math.floor(e.x/TS)-9;x<=Math.floor(e.x/TS)+9;x++)if(tAt(x,y)===T.AIR&&(x+y)%4===0&&Math.hypot((x+.5)*TS-P.x,(y+.5)*TS-P.y)>25){tiles[I(x,y)]=T.SAP;redraw(x,y)}}}
 e.cd-=dt;if(e.cd<=0){e.cd=ph===1?3.5:ph===2?3:4;const noisy=P.sw>0||Math.hypot(P.vx,P.vy)>45||dyns.length;const flare=nearFlare(e);if(ph===1){const target=flare||P;zones.push({x:target.x,y:target.y,r:noisy?44:25,t:0,T:noisy?1.2:1.8,dmg:e.dmg});SND.gwind(e.x)}else if(ph===2){for(const off of [-48,48])zones.push({x:P.x+off,y:P.y,r:28,t:0,T:1.6,dmg:e.dmg});}else{eventSpawn({x:e.x,y:e.y,k:e.k},'memoryhusk',2);zones.push({x:P.x,y:P.y,r:35,t:0,T:1.5,dmg:e.dmg});}e.st='recover';e.t=1.8}
 e.t-=dt;if(e.t<=0)e.st='listen';
}
function endingName(id){return {sever:'The Severing',accord:'The Accord',seal:'The Sleeping Seal'}[id]}
function sovereignDefeated(){RUN.pendingEnding=true;S.boss.sovereign=1;S.won=true;RUN.x.boss++;beat('resolution');relic('heart');SND.bossDie();boss=null;for(const e of enemies)e.dead=true;zones=[];projs=[];save();rootChoice()}
function rootChoice(){say('The Root’s Heart','The Sovereign is silent. Iona waits beside the last memory. What will this camp become?',[
 {label:'The Severing · end its hunger; the garden becomes a memorial',go:()=>resolveEnding('sever')},
 {label:'The Accord · preserve the ecosystem; rescue 3 echoes or research the Accord',disabled:!(S.exp.flags.accord||S.exp.rescues+RUN.x.rescued>=3),go:()=>resolveEnding('accord')},
 {label:'The Sleeping Seal · restore containment; study the charter first',disabled:!(S.exp.flags.seal||S.exp.relics.charter),go:()=>resolveEnding('seal')}
 ])}
function resolveEnding(id){if(!['sever','accord','seal'].includes(id))return;RUN.pendingEnding=false;const first=!S.exp.ending.includes(id);if(first){S.exp.ending.push(id);S.wins++;S.mats.seed=(S.mats.seed||0)+3;S.mats.rootsteel=(S.mats.rootsteel||0)+5;S.exp.protected.seed=1;S.exp.projects.garden=1;S.exp.visited.garden=1;S.exp.ench.pick='rootcarver';}S.exp.flags['ending_'+id]=1;CAMP.notice=id==='sever'?'The garden is a memorial. The roots fall quiet.':id==='accord'?'The camp tends the Root. Iona comes home carrying a seed.':'The old seal holds. Blue lights now keep watch at camp.';closeStory();RUN.won=1;endRun(true)}
function improveHit(e,dm){if(state!=='run'||!RUN?.x)return dm;const melee=P.swk==='sword'&&P.sw>0;if(melee&&ench('sword','ripper'))e.bleed=3;if(melee&&ench('sword','frostbrand'))e.slow=2.5;if(melee&&ench('sword','bulwark')){e.slow=1;e.cd=Math.max(1,e.cd)}if(melee&&ench('sword','echo')&&!e.echo){e.echo=.6;e.echoDmg=dm*.4}return dm*(RUN.x.blessed?1.15:1)*(melee&&S.exp.projects.training?1.1:1)}
function enemyEffects(e,dt){if(e.dead)return true;if(e.distract>0){e.distract-=dt;e.al=0;return true}if(e.bleed>0){e.bleed-=dt;e.hp-=2*dt;if(e.hp<=0){hurtEnemy(e,1,0,0);return true}}if(e.echo>0){e.echo-=dt;if(e.echo<=0){const amount=e.echoDmg;e.echoDmg=0;const sw=P.sw;P.sw=0;hurtEnemy(e,amount,0,0);P.sw=sw;return !!e.dead}}return false}
function enemyReward(e){if(!RUN?.x)return;RUN.x.kills++;if(RUN.x.condition==='migration')P.oil=Math.min(P.moil,P.oil+3);if(ACT===2)RUN.x.attention+=2;if(ROOT_TYPES.has(e.type)&&!e.boss){drop(e.type==='leech'?'amber':e.type==='woodgolem'?'heartwood':e.type==='choir'?'memory':'rootsteel',e.x,e.y);if(e.stolen)for(let i=0;i<e.stolen;i++)drop('amber',e.x,e.y);if(e.type==='foreman'){relic('badge');drop('seed',e.x,e.y)}if(e.type==='choir')relic('song')}}

// Multi-part camp buildings use a cached ground layer and small animated details.
function campPerson(x,y,color,walk=0,hat=true){x=Math.round(x);y=Math.round(y);const bob=Math.floor(walk/8)%2;px(x-5,y+3,10,3,'#17221ed0');px(x-3,y,2,5-bob,'#222a2b');px(x+2,y,2,4+bob,'#222a2b');px(x-4,y-9,9,10,color);px(x-3,y-8,2,5,'#ffffff28');px(x-6,y-6+bob,2,6,'#a77755');px(x+5,y-6-bob,2,6,'#bc9473');px(x-3,y-15,6,6,'#c49a77');px(x+2,y-13,1,1,'#17222b');px(x-3,y-10,5,1,'#805638');if(hat){px(x-4,y-17,8,3,'#b39a5b');px(x-5,y-14,10,1,'#e3c888');px(x+3,y-16,2,2,'#fff0b9')}}
function drawPOIs(camx,camy){for(const p of POIS){const x=Math.round(p.x-camx),y=Math.round(p.y-camy);if(x< -40||x>VW+40||y< -40||y>VH+40)continue;const seen=p.seen||p.critical||RUN?.x?.condition==='echoes',gold=p.contract?'#73a6aa':ACT===2?'#aa8849':'#a4936c';if(!seen&&lightAt(p.x,p.y)<.08)continue;
 px(x-18,y+4,36,9,'#101713a0');if(['shrine','temple','court','ritual'].includes(p.kind)){for(let i=0;i<3;i++)px(x-16+i*13,y-16-i%2*6,5,25,p.done?'#465348':'#797b62');px(x-18,y-18,36,3,'#aea17a');px(x-13,y+3,26,4,'#535c4f')}
 if(['beacon','object','speed'].includes(p.kind)){px(x-2,y-29,4,27,'#7b8f85');px(x-10,y-22,20,2,gold);px(x-7,y-26,14,2,'#a7c5af');px(x-5,y-7,10,10,'#9f8550');px(x-3,y-5,6,3,p.done?'#51684f':gold)}
 else if(['shrine','temple','court','ritual'].includes(p.kind)){for(let i=0;i<4;i++)px(x-12+i*2,y-i*4,24-i*4,4,'#778571');px(x-3,y-20,6,6,gold)}
 else if(['memory','echo','rescue','memorial','shelter'].includes(p.kind)){cx.globalAlpha=.7+Math.sin(TT*3)*.2;campPerson(x,y-1,p.done?'#667462':gold,0,false);cx.globalAlpha=1;}
 else if(['nest','nursery','garden'].includes(p.kind)){for(let i=0;i<6;i++){px(x-12+i*5,y-2-Math.sin(i)*3,4,6,'#bfa175');px(x-11+i*5,y-8-Math.sin(i)*3,3,7,gold)}}
 else{px(x-11,y-12,23,17,'#8e704c');px(x-10,y-12,21,2,'#c9ad70');px(x-11,y-5,23,2,'#313f35');px(x-2,y-6,4,5,gold)}
 if(!p.done&&(p.contract||Math.hypot(p.x-P.x,p.y-P.y)<52)){cx.fillStyle=gold;cx.font='8px monospace';cx.textAlign='center';cx.fillText(p.critical?'SIGNAL':'◇',x,y-34-Math.sin(TT*2)*2);cx.textAlign='left'}
 }
 if(RUN?.x){const goal=POIS.find(p=>p.contract&&!p.done);if(goal&&Math.hypot(goal.x-P.x,goal.y-P.y)>100){const a=Math.atan2(goal.y-P.y,goal.x-P.x),x=VW/2+Math.cos(a)*72,y=VH/2+Math.sin(a)*60;cx.save();cx.translate(x,y);cx.rotate(a);cx.fillStyle='#80dddc';cx.beginPath();cx.moveTo(5,0);cx.lineTo(-3,-3);cx.lineTo(-3,3);cx.fill();cx.restore()}}
}
function drawRootEnemy(e,camx,camy){if(!ROOT_TYPES.has(e.type))return false;const x=Math.round(e.x-camx),y=Math.round(e.y-camy);if(x<-60||y<-60||x>VW+60||y>VH+60)return true;cx.globalAlpha=e.alpha||1;const c=e.fl>0?'#fff0c0':e.type==='memoryhusk'?'#84c9c5':e.type==='pollenwitch'?'#a77ea8':'#78936b';
 if(e.type==='memoryhusk'){drawEnemy({...e,type:e.memoryForm||'crawler',alpha:.7},camx,camy);px(x-4,y-10,8,1,'#94eadb');cx.globalAlpha=1;return true}if(e.boss){px(x-34,y+12,68,10,'#101c18');for(let i=0;i<9;i++){const a=i/9*6.28;cx.strokeStyle=e.fl>0?'#e6d6ad':'#7d7950';cx.lineWidth=3;cx.beginPath();cx.moveTo(x,y);cx.quadraticCurveTo(x+Math.cos(a)*35,y+Math.sin(a)*20-10,x+Math.cos(a)*55,y+Math.sin(a)*36+6);cx.stroke()}for(let i=0;i<6;i++)px(x-22+i*3,y-18-i*4,44-i*6,24+i*2,i%2?'#737953':'#525f43');px(x-11,y-22,22,24,'#202f28');px(x-6,y-16,12,14,e.ph===3?'#a1e9d1':e.ph===2?'#ecb454':'#d4d190');px(x-3,y-14,4,9,'#ffffd1');for(const s of [-1,1]){px(x+s*17,y-28,5,10,'#b0aa75');px(x+s*19,y-34,2,8,'#e3d89b')}cx.font='8px monospace';cx.textAlign='center';cx.fillStyle='#e9d8a2';cx.fillText(e.st==='recover'?'OPEN HEART':e.ph===1?'LISTENING':e.ph===2?'FLOODING':'MEMORY',x,y-49);cx.textAlign='left';}
 else if(['mimic','memoryhusk','foreman'].includes(e.type)){campPerson(x,y,c,e.an*20,e.type!=='memoryhusk');if(e.type==='foreman'){px(x-12,y-10,6,12,'#a88b60');px(x+7,y-12,7,5,'#aebdaf')}}
 else if(e.type==='rootbat'){const flap=Math.sin(e.an*15)*4;px(x-3,y-5,6,9,c);for(const s of [-1,1]){px(x+s*6-3,y-6+flap,7,2,c);px(x+s*10-2,y-3+flap,4,2,'#adb887')}px(x-1,y-4,2,2,'#f4d77d')}
 else if(e.type==='leech'){for(let i=0;i<6;i++)px(x-7+i*3,y-3+Math.sin(e.an*7+i)*2,4,5,i%2?'#c99a4f':'#8d683a');px(x+9,y-3,2,2,'#fff2b4')}
 else{const size=e.type==='woodgolem'?12:e.type==='choir'?9:7;px(x-size,y+4,size*2,3,'#17231c');for(let i=0;i<4;i++)px(x-size+i*2,y-15-i*2,size*2-i*4,20+i*2,i%2?c:'#445e47');for(const s of [-1,1]){px(x+s*(size+1),y-8,2,13,c);px(x+s*3,y-12,2,2,e.type==='pollenwitch'?'#ffeaaa':'#efc668')}if(e.type==='woodgolem'&&!e.anchorCut){cx.strokeStyle='#c6b15a';cx.beginPath();cx.moveTo(x,y);cx.lineTo(e.anchor?.x-camx||x-20,e.anchor?.y-camy||y);cx.stroke()}if(e.type==='choir'){for(let i=0;i<3;i++)px(x-9+i*8,y-23-i%2*5,3,12,'#bac9a0')}}
 if(e.st==='wind'){cx.strokeStyle='#ffc172';cx.beginPath();cx.arc(x,y,16,0,6.28);cx.stroke()}
 cx.globalAlpha=1;return true;
}
function setupExpansionUI(){
 $('storybox').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(!b||b.disabled||!dialogue)return;const c=dialogue.choices[+b.dataset.choice];c?.go()});
 $('interact').addEventListener('click',()=>state==='surface'?campInteract():interactWorld());
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
 if(d.slot!==undefined){e.stopImmediatePropagation();if(state==='run'&&!paused)selectSlot(+d.slot);return}if(d.field){e.stopImmediatePropagation();useUtility(d.field);return}const recognized=['route','exp','station','project','refine','enchant','lock','utility','contract','condition','loadout','research','mastery','test','request'].some(k=>d[k]!==undefined);if(!recognized)return;e.stopImmediatePropagation();AU.init();SND.ui();
 if(d.route&&STATION_SIGNS[d.route]){CAMP.destination=d.route;CAMP.route=null;closeCamp();return}if(d.exp==='guide'){openCamp('guide');return}if(d.exp==='close'){closeCamp();return}if(d.exp==='quick'){openCamp('quick');return}if(d.exp==='journal'){if(state==='surface')openCamp('journal');return}if(d.exp==='menu'){save();CAMP.active=false;CAMP.menu=null;$('campbar').style.display='none';$('interact').style.display='none';$('touch-controls').classList.remove('on');showMenu();return}if(d.exp==='talk'){say('Old Marrow',npcLine({id:'marrow',who:'Old Marrow'}),[{label:'Return to camp',go:()=>{closeStory();closeCamp()}}]);return}if(d.exp==='daily')S.exp.seedText='SIGNAL-'+new Date().toISOString().slice(0,10);
 if(d.station&&S.exp.visited[d.station]){openCamp(d.station);return}
 if(d.project){const p=PROJECTS.find(p=>p.id===d.project);if(p&&!S.exp.projects[p.id]&&canPay(p.c,p.m)){pay(p.c,p.m);S.exp.projects[p.id]=1;CAMP.notice=p.d;SND.craft();toast(`<b>${p.n} RESTORED</b><br>${p.benefit}`);}}
 if(d.refine){const r=RECIPES.find(r=>r.id===d.refine),mode=d.mode;if(r&&['safe','hot','pure'].includes(mode)&&S.exp.projects.smelter){const c=scaleCost(r.c,mode==='hot'?2:1),m=mode==='hot'?15:mode==='pure'?25:0;if(canPay(c,m)){pay(c,m);S.mats[r.id]=(S.mats[r.id]||0)+(mode==='hot'?2:1);S.exp.protected[r.id]=1;if(mode==='pure')S.exp.flags.ward=true;SND.craft()}}}
 if(d.enchant){const e=ENCHANTS[d.gear]?.find(e=>e.id===d.enchant);if(e&&S.exp.projects.forge&&S.gear[d.gear]>=0&&!ench(d.gear,e.id)&&canPay(e.c)){pay(e.c);S.exp.ench[d.gear]=e.id;SND.craft();toast(`<b>${e.n}</b> equipped · ${e.tag}`)}}
 if(d.lock&&ITEMS[d.lock])S.exp.protected[d.lock]=!S.exp.protected[d.lock];
 if(d.utility){const u=UTILITIES.find(u=>u.id===d.utility);if(u&&S.exp.projects.workshop&&canPay(u.c)&&(S.cons[u.id]||0)<5){pay(u.c);S.cons[u.id]=(S.cons[u.id]||0)+1;SND.craft()}}
 if(d.contract&&availableContracts().some(c=>c.id===d.contract))S.exp.contract=d.contract;
 if(d.condition&&CONDITIONS.some(c=>c.id===d.condition))S.exp.condition=d.condition;
 if(d.loadout&&['surveyor','warden','porter'].includes(d.loadout))S.exp.loadout=d.loadout;
 if(d.research==='accord'&&S.exp.projects.garden&&!S.exp.flags.accord&&canPay({record:1})){pay({record:1});S.exp.flags.accord=true}
 if(d.research==='seal'&&S.exp.relics.charter)S.exp.flags.seal=true;
 if(d.mastery){const m=MASTERY.find(m=>m[0]===d.mastery);if(m&&masteryValue(m[0])>=m[2]&&!S.exp.mastery[m[0]]){S.exp.mastery[m[0]]=1;S.money+=300;S.mats.relic=(S.mats.relic||0)+1;S.exp.protected.relic=1;SND.quest()}}
 if(d.request){const r=REQUESTS[d.request];if(r&&r.ready()&&!S.exp.flags['request_'+d.request]){S.exp.flags['request_'+d.request]=1;r.grant();S.exp.trust[d.request]=(S.exp.trust[d.request]||0)+2;for(const k in S.mats)if(ITEMS[k]?.refined)S.exp.protected[k]=1;SND.quest()}}if(d.test){const g=d.test,idx=S.gear[g];$('training-result').textContent=idx<0?'Forge a weapon first.':`${GEAR[g][idx].n}: ${g==='pick'?pw().toFixed(1)+' mining power':GEAR[g][idx].dmg+' base damage'}. Branch: ${ENCHANTS[g].find(e=>e.id===S.exp.ench[g])?.d||'None equipped.'}`;SND.ehit(0);return}
 save();renderSurface();
 },true);
 $('surf').addEventListener('change',e=>{if(e.target.id==='variant-choice')S.exp.variant=e.target.value;if(e.target.id==='seed-choice')S.exp.seedText=e.target.value.replace(/[^a-zA-Z0-9-]/g,'').slice(0,32);save()});
 addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.repeat)return;if(state==='surface'&&!dialogue){if(k==='escape'&&CAMP.menu){closeCamp();return}if(k==='?'||k==='/'){e.preventDefault();openCamp('guide')}if(k==='c')openCamp('quick');if(k==='j')openCamp('journal');if(!CAMP.menu&&(k==='e'||k===' ')){e.preventDefault();campInteract()}}if(state==='run'&&!paused){if(k==='z')useAbility();if(k==='b')useUtility('bridge');if(k==='g')useUtility('decoy');if(k==='h')useUtility('heat');if(k==='v')useUtility('recorder');if(k==='y')useUtility('sapcharge')}});
 addEventListener('storage',e=>{if(e.key===SKEY&&(state==='run'||state==='surface')){storageLocked=true;storageWarning='This character changed in another tab. Reload before continuing, or export this tab’s character as a separate backup.';clearInputs();paused=true;if(state==='run')showPanel('pause');toast(storageWarning)}});
 addEventListener('pagehide',()=>{if(state==='run'||state==='surface')save()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(state==='run'&&!paused)togglePause();if(state==='run'||state==='surface')save()}});
}
Object.assign(EB,{skater:{hp:16,dmg:17,spd:65,hw:5},frostchoir:{hp:32,dmg:15,spd:0,hw:7},mirrorling:{hp:20,dmg:17,spd:48,hw:5}});
Object.assign(ENAME,{skater:'SHARD SKATER',frostchoir:'RIME CANTOR',mirrorling:'MIRRORLING'});
function frozenEnemy(e,dt){if(!['skater','frostchoir','mirrorling'].includes(e.type))return false;const dx=P.x-e.x,dy=P.y-e.y,d=Math.hypot(dx,dy)||1;if(d>360)return true;e.cd-=dt;e.t-=dt;e.acd-=dt;e.an+=dt;e.fl-=dt;e.slow=Math.max(0,e.slow-dt);const vis=d<180&&los(e.x/TS|0,e.y/TS|0,P.x/TS|0,P.y/TS|0),fl=nearFlare(e);
 if(e.type==='skater'){if(e.st==='idle'&&vis&&e.cd<=0){e.st='wind';e.t=.9;SND.chit(e.x);hintOnce('skater','<b>Shard Skaters</b> cannot turn during a charge. Let them pass, then strike during recovery.')}if(e.st==='wind'&&e.t<=0){e.cx=dx/d;e.cy=dy/d;e.st='charge';e.t=.7}if(e.st==='charge'){moveBox(e,e.cx*160*dt,e.cy*160*dt,e.hw,0);if(e.t<=0){e.st='rec';e.t=1.4}}if(e.st==='rec'&&e.t<=0){e.st='idle';e.cd=1}if(e.st==='charge'&&d<15&&e.acd<=0){hurtPlayer(e.dmg,dx/d,dy/d);e.acd=1}}
 else if(e.type==='frostchoir'){if(vis&&e.cd<=0&&!fl){e.cd=4;zones.push({x:P.x,y:P.y,r:32,t:0,T:1.8,dmg:e.dmg});for(const q of enemies)if(!q.boss&&q!==e&&Math.hypot(q.x-e.x,q.y-e.y)<100)q.hp=Math.min(q.mhp,q.hp+3);SND.wraith(e.x);hintOnce('cantor','The <b>Rime Cantor</b> restores its allies. A flare silences its song.')}}
 else if(vis){if(!fl)moveBox(e,-P.vx*dt*.8,-P.vy*dt*.8,e.hw,0);if(e.cd<=0){e.cd=3;e.st='wind';e.t=.8}if(e.st==='wind'&&e.t<=0){e.st='idle';eshoot(e.x,e.y,Math.atan2(dy,dx),120,e.dmg,'ice');SND.shoot('frost')}hintOnce('mirrorling','The <b>Mirrorling</b> reverses your movement. Use the walls to trap its reflection.')}
 return true;
}
function drawFrozenEnemy(e,camx,camy){if(!['skater','frostchoir','mirrorling'].includes(e.type))return false;const x=Math.round(e.x-camx),y=Math.round(e.y-camy),c=e.fl>0?'#ffffff':'#96c4d5';if(e.type==='skater'){px(x-8,y+3,16,2,'#bfdfea');px(x-5,y-7,10,10,'#567f96');px(x-3,y-12,6,6,c);px(x-9,y-2,3,5,c);px(x+6,y-2,3,5,c)}else if(e.type==='frostchoir'){for(let i=0;i<5;i++)px(x-10+i*5,y-18-Math.sin(i)*5,3,23,c);px(x-8,y-10,16,4,'#456380');px(x-2,y-8,4,4,'#d5edf3')}else{cx.globalAlpha=.8;campPerson(x,y,c,e.an*8,false);cx.globalAlpha=1;px(x-1,y-13,3,1,'#e9faff')}if(e.st==='wind'){cx.strokeStyle='#b7e8ff';cx.beginPath();cx.arc(x,y,15,0,6.28);cx.stroke()}return true}
function decorateVariant(p,v){const tx=p.x/TS|0,ty=p.y/TS|0;for(let j=-8;j<=8;j++)for(let i=-9;i<=9;i++){const x=tx+i,y=ty+j;if(!inB(x,y)||Math.abs(i)<3||Math.abs(j)<3)continue;const q=I(x,y);if(tiles[q]!==T.AIR)continue;const h=ih(x,y,WSEED);if(v.id==='redwater'&&h>.3)tiles[q]=T.WATER;if(v.id==='glass'&&h>.3)tiles[q]=T.ICEFLOOR;if(v.id==='ash'&&h>.5){flg[q]|=1;decor[q]=11}if(v.id==='cathedral'){decor[q]=5;if(h>.97)slights.push({x:(x+.5)*TS,y:(y+.5)*TS,r:3,c:[.3,.15,.4],fl:0})}if(v.id==='rust')decor[q]=6;if(v.id==='blue'&&h>.9)decor[q]=14;if(v.id==='starfall'&&h>.85){tiles[q]=T.STARMETAL;flg[q]|=1}}}
function offerRootGate(){const p=POIS.find(p=>p.gate&&Math.hypot((p.gate.x+.5)*TS-P.x,(p.gate.y+.5)*TS-P.y)<48&&tAt(p.gate.x,p.gate.y)===T.ROOT);if(!p)return false;const open=()=>{tiles[I(p.gate.x,p.gate.y)]=T.AIR;redraw(p.gate.x,p.gate.y);p.gate.clock=-60;closeStory();save();SND.heal()};say('The Listening Gate','A living root crosses this optional passage. It turns toward your lamp. You can also cut it with your pickaxe.',[{label:'Offer one carried Amber Sap',disabled:!P.pack.includes('amber'),go:()=>{P.pack.splice(P.pack.indexOf('amber'),1);packDirty=true;RUN.x.attention=Math.max(0,RUN.x.attention-10);open()}},{label:'Sing with a flare',disabled:!S.cons.flare,go:()=>{S.cons.flare--;open()}},{label:'Leave it',go:closeStory}]);return true}
const portraits=new Map();
function portraitFor(name){if(portraits.has(name))return portraits.get(name);const c=document.createElement('canvas');c.width=40;c.height=48;const g=c.getContext('2d');let h=0;for(const ch of name)h=(h*31+ch.charCodeAt(0))>>>0;const rect=(x,y,w,z,col)=>{g.fillStyle=col;g.fillRect(x,y,w,z)};rect(0,0,40,48,'#1b302f');for(let i=0;i<7;i++)rect(i*7-9,0,2,48,'#24403a');rect(5,37,31,11,'#4b6964');rect(9,34,22,14,'#6a8170');rect(14,32,12,7,'#996e50');rect(11,12,19,23,'#b98e68');rect(11,15,4,16,'#976849');rect(15,13,13,7,'#d5b088');rect(9,20,3,8,'#ac7e58');rect(30,20,3,8,'#bd936b');rect(15,22,5,2,'#403d30');rect(24,22,5,2,'#403d30');rect(17,24,2,2,'#d8e2c7');rect(25,24,2,2,'#d8e2c7');rect(21,24,2,6,'#e3b188');rect(17,32,10,1,'#754a37');rect(10,10,21,5,h%2?'#887a56':'#b4aaa0');rect(10,15,3,6,'#706454');if(name.includes('Marrow')){rect(13,30,6,6,'#adac91');rect(24,30,6,6,'#b9b498');rect(16,35,11,3,'#b9b498');rect(8,8,25,4,'#757b5b')}else{rect(8,9,25,5,'#a6955d');rect(6,14,29,2,'#d1ba75');rect(18,8,7,6,'#e4d89d');rect(20,9,3,4,'#fff4c0')}rect(17,39,2,9,'#b3aa7c');rect(26,39,2,9,'#b3aa7c');const url=c.toDataURL();portraits.set(name,url);return url}
function mapRoomHTML(){return `<h3>THE SHAFT ATLAS</h3><div class='grid'>${ACTS.map((a,i)=>`<article class='card'><h3>${a.name}</h3><p>${S.unl[i]||0}/${a.layers.length} lifts restored · ${S.exp.actEscapes[i]} returns</p>${a.layers.map((l,k)=>`<div class='row ${k<=S.reached[i]?'':'dim'}'><span>${l.name}</span><span>${k<(S.unl[i]||0)?'LIFT':k<=S.reached[i]?'SEEN':'?'}</span></div>`).join('')}</article>`).join('')}</div><p class='sec'>Recent expedition seeds: ${S.exp.telemetry.slice(-5).map(t=>t.seed||'Unrecorded').join(' · ')||'None yet'}</p>`}
