(async()=>{
 const results=[],assert=(name,ok,detail='')=>{results.push({name,pass:!!ok,detail});if(!ok)throw Error(name+': '+detail)};
 const old=localStorage.getItem(SKEY);paused=true;restoreMode=true;
 try{
  const base=defSave();applySaveData({v:2,money:150,gear:{pick:2},stats:{runs:4},mats:{copper:8},up:{pack:999},unl:[2,0],set:{music:2}});
  assert('v2 migration retains progress and clamps upgrades',S.v===3&&S.money===150&&S.gear.pick===2&&S.mats.copper===8&&lv('pack')===5&&S.set.music===1&&S.unl.length===3);
  applySaveData({up:{pick:3},unlocked:3});assert('unversioned v1 migration',S.gear.pick===3&&S.unl[0]===3);
  applySaveData({v:2,gear:{pick:NaN,sword:999},money:Infinity,stats:{time:-2,kt:null},cons:{tonic:-3},mats:{fake:2,coal:NaN},set:{shake:-1},exp:{journal:[{},'<b>'],condition:'fake'}});
  assert('invalid and missing nested values recover',S.money===0&&S.stats.time===0&&S.cons.tonic===0&&S.gear.sword===SWORDS.length-1&&S.mats.fake===undefined&&S.exp.journal.length===0);
  applySaveData(base);S.exp.flags.extraction=1;S.exp.flags.arrival=1;S.exp.flags.briefed=1;S.exp.condition='calm';S.gear.pick=8;
  const reach=(start)=>{const seen=new Uint8Array(tiles.length),queue=[I(start.x,start.y)];seen[queue[0]]=1;for(let h=0;h<queue.length;h++){const id=queue[h],x=id%MW,y=Math.floor(id/MW);for(const [dx,dy] of D4){const X=x+dx,Y=y+dy;if(!inB(X,Y))continue;const i=I(X,Y),t=tiles[i];if(!seen[i]&&(!TI[t].solid||t===T.BARRIER)){seen[i]=1;queue.push(i)}}}return seen};
  const hash=arr=>{let h=2166136261;for(const n of arr)h=Math.imul(h^n,16777619);return h>>>0};
  let generated=0;
  for(let a=0;a<3;a++)for(let seed=1;seed<=12;seed++){S.act=a;S.startL=0;S.exp.contract=a===2?'sap':a===1?'cold':'relay';setAct(a);genWorld(seed);const h=hash(tiles),objects=JSON.stringify(gItems);genWorld(seed);assert(`deterministic act ${a} seed ${seed}`,h===hash(tiles)&&objects===JSON.stringify(gItems));const seen=reach(lifts[0]);const bad=POIS.filter(p=>!seen[I(Math.floor(p.x/TS),Math.floor(p.y/TS))]);assert(`reachable landmarks act ${a} seed ${seed}`,bad.length===0,JSON.stringify(bad.map(p=>p.id)));assert(`reachable boss act ${a} seed ${seed}`,!!seen[I(Math.floor(bossSpawn.x/TS),Math.floor(bossSpawn.y/TS))]);generated++;}
  S=defSave();S.exp.flags.arrival=1;S.exp.flags.briefed=1;S.exp.flags.extraction=1;S.up.salv=1;S.exp.contract='copper';restoreMode=false;S.exp.seedText='1001';startRun(0,0);paused=true;
  P.pack=['copper','copper','copper','copper','copper','copper'];RUN.x.progress=1;RUN.t=123;const money=S.money;endRun(true);assert('contract payout and bank on extraction',S.exp.contracts===1&&S.money>money&&S.mats.copper===8);const after=S.money;endRun(true);assert('results cannot duplicate rewards',S.money===after);enterCamp();assert('extraction returns to walkable camp',state==='surface'&&!CAMP.menu&&!P);
  S.exp.contract='fragile';S.exp.seedText='1002';startRun(0,0);paused=true;P.pack=['diamond','gold','coal'];RUN.x.progress=1;RUN.x.fragile=true;P.inv=0;hurtPlayer(1,0,0);assert('fragile cargo reacts to damage',RUN.x.fragileBroken);endRun(false);assert('death banks best salvage and fails contract',S.mats.diamond===1&&S.mats.gold===1&&S.exp.failed===1);enterCamp('death');assert('death respawns at infirmary',CAMP.x===76&&CAMP.y===215);
  S.mats.iron=10;S.exp.protected.iron=1;const wallet=S.money;sell('iron','all');assert('protected inventory cannot be sold',S.mats.iron===10&&wallet===S.money);
  S.exp.contract='survey';S.exp.seedText='773';startRun(1,0);paused=true;P.pack=['frostite'];RUN.x.progress=0;P.oil=140;S.cons.flare=2;save();const cp=JSON.parse(localStorage.getItem(SKEY)).checkpoint;assert('run checkpoint validates',validCheckpoint(cp));const rs=S.stats.runs,cons=S.cons.flare;S.checkpoint=cp;resumeExpedition();assert('reload restores simulation without run inflation',state==='run'&&paused&&P.pack[0]==='frostite'&&P.oil===140&&S.stats.runs===rs&&S.cons.flare===cons);
  const invalid=JSON.parse(JSON.stringify(cp));invalid.player.x=NaN;assert('malformed checkpoint rejected',!validCheckpoint(invalid));
  S.exp.flags.extraction=1;S.exp.seedText='201';S.exp.contract='master';startRun(2,4);paused=true;const root=boss;P.x=root.x-110;P.y=root.y;root.st='sleep';sovereignAI(root,.1);assert('Sovereign listening phase',root.ph===1&&root.st!=='sleep');root.hp=root.mhp*.6;sovereignAI(root,.1);assert('Sovereign flooding phase',root.ph===2&&tiles.includes(T.SAP));root.hp=root.mhp*.25;sovereignAI(root,.1);assert('Sovereign memory phase',root.ph===3);S.exp.flags.seal=true;S.exp.flags.accord=true;hurtEnemy(root,10000,0,0);assert('Sovereign choice pauses simulation',!!dialogue&&paused&&S.boss.sovereign);resolveEnding('accord');assert('Accord resolves and unlocks garden/tool',S.exp.ending.includes('accord')&&S.exp.projects.garden&&S.exp.ench.pick==='rootcarver'&&state==='results');
  const round=JSON.parse(JSON.stringify(S));applySaveData(round);assert('expansion progression survives migration',S.exp.ending.includes('accord')&&S.exp.projects.garden&&S.exp.ench.pick==='rootcarver');
  return {passed:results.filter(r=>r.pass).length,generated,results};
 }catch(e){return {error:e.stack,results}}finally{restoreMode=true;state='menu';dialogue=null;paused=false;S=defSave();if(old){localStorage.setItem(SKEY,old);applySaveData(JSON.parse(old))}else localStorage.removeItem(SKEY);restoreMode=false;S.exp.seedText='';CAMP.active=false;CAMP.menu=null;P=null;RUN=null;setAct(0);genWorld(4242);showMenu()}
})()
