(async()=>{
 const old=localStorage.getItem(SKEY),checks=[];const check=(n,v)=>{checks.push({name:n,pass:!!v});if(!v)throw Error(n)};
 try{
  state='menu';S=defSave();S.exp.flags.arrival=1;S.exp.flags.briefed=1;S.exp.flags.extraction=1;S.exp.seedText='10101';S.exp.contract='rescue';startRun(0,0);paused=true;P.oil=100;const p=POIS.find(p=>p.contract);P.x=p.x;P.y=p.y;eventDialog(p);document.querySelector('[data-choice="1"]').click();check('abandoned rescue does not complete contract',!contractSuccess(true));
  endRun(false);S.exp.contract='nest';startRun(0,0);paused=true;S.cons.flare=1;const nest=POIS.find(p=>p.contract);eventDialog(nest);document.querySelector('[data-choice="1"]').click();check('protected nest does not complete destruction contract',!contractSuccess(true));
  paused=false;P.hp=P.mhp;const used=RUN.x.tonics;useTonic();check('full-health tonic attempt does not fail challenge',RUN.x.tonics===used);S.cons.tonic=1;P.hp=P.mhp-40;useTonic();check('tonic checkpoint includes heal',JSON.parse(localStorage.getItem(SKEY)).checkpoint.player.hp===P.hp);
  S.cons.rope=1;useRope();const time=P.rope;togglePause();for(let i=0;i<20;i++)tickUI(.1);check('rope frozen during pause',P.rope===time);togglePause();for(let i=0;i<70&&state==='run';i++)update(.05);check('rope extracts and consumes one item',state==='results'&&S.cons.rope===0);
  startRun(0,0);P.pack=['coal'];die();save();S.checkpoint=JSON.parse(localStorage.getItem(SKEY)).checkpoint;resumeExpedition();check('dead checkpoint resolves to results',state==='results');
  S.exp.flags.extraction=1;S.exp.contract='memory';S.exp.condition='migration';S.exp.loadout='warden';S.exp.seedText='98765';startRun(2,0);paused=true;check('numeric share seed exact',RUN.x.seed===98765);const hp=P.mhp;check('warden changes loadout',hp===130&&P.cap===7);const oil=P.oil;enemyReward(mkEnemy('leech',P.x+50,P.y,0));check('migration kill oil capped safely',P.oil===Math.min(P.moil,oil+3));
  S.exp.seedText='9123';S.exp.contract='survey';S.exp.loadout='surveyor';startRun(2,0);paused=true;P.pack=['amber','amber','amber','amber'];const att=RUN.x.attention;updateExpansion(1);check('sap burden raises attention',RUN.x.attention>att);RUN.x.attention=70;S.cons.recorder=1;paused=false;useUtility('recorder');check('recorder calms root attention',RUN.x.attention===40&&S.cons.recorder===0);
  const x=P.x/TS|0,y=(P.y/TS|0)+2;tiles[I(x,y)]=T.CHASM;M.x=(x+.5)*TS-camX0;M.y=(y+.5)*TS-camY0;S.cons.bridge=1;useUtility('bridge');check('bridge opens route',tiles[I(x,y)]===T.AIR&&S.cons.bridge===0);
  S.cons.heat=1;useUtility('heat');const before=P.hp;envHurt(10);check('heat pack blocks hazard damage',P.hp===before&&RUN.x.heat===45);
  clearInputs();K.w=true;M.l=true;dispatchEvent(new Event('blur'));check('focus loss pauses and clears held input',paused&&!K.w&&!M.l);
  paused=false;S.cons.dyn=2;selectSlot(3);const ds=dyns.length;cv.dispatchEvent(new MouseEvent('mousedown',{button:0,clientX:200,clientY:200,bubbles:true}));dispatchEvent(new MouseEvent('mouseup',{button:0}));check('short click consumes selected dynamite immediately',dyns.length===ds+1&&S.cons.dyn===1&&!M.l);S.exp.contract='memory';startRun(2,0);paused=true;const memory=POIS.find(p=>p.contract);eventDialog(memory);document.querySelector('[data-choice="0"]').click();check('memory rescue counts echoes rather than glass inventory',RUN.x.rescued===1&&contractSuccess(true));dispatchEvent(new StorageEvent('storage',{key:SKEY,newValue:'{}'}));check('another tab cannot silently overwrite active character',storageLocked&&paused);storageLocked=false;storageWarning='';return {passed:checks.length,checks};
 }catch(e){return {error:e.stack,checks}}finally{state='menu';restoreMode=true;P=null;RUN=null;dialogue=null;paused=false;CAMP.active=false;CAMP.menu=null;S=defSave();if(old){localStorage.setItem(SKEY,old);applySaveData(JSON.parse(old))}else localStorage.removeItem(SKEY);restoreMode=false;setAct(0);genWorld(4242);showMenu()}
})()
