(async()=>{
 const old=localStorage.getItem(SKEY),oldConfirm=window.confirm,rows=[];const check=(name,ok)=>{rows.push({name,pass:!!ok});if(!ok)throw Error(name)};
 const click=sel=>{const e=document.querySelector(sel);if(!e||e.disabled)throw Error('Unavailable control '+sel);e.click()};
 try{
  state='menu';S=defSave();S.exp.flags.arrival=1;S.exp.flags.briefed=1;S.exp.flags.extraction=1;S.money=10000;for(const k in ITEMS)if(!ITEMS[k].use)S.mats[k]=30;enterCamp();CAMP.x=174;CAMP.y=112;updateCamp(.016);campInteract();check('physical refinery discovery',CAMP.menu==='smelter'&&S.exp.visited.smelter);click('[data-project="smelter"]');check('camp project purchased',S.exp.projects.smelter&&S.money===9975);
  for(const id of ['cbar','ibar','alloy']){const oldN=S.mats[id];click(`[data-refine="${id}"][data-mode="safe"]`);check('refine '+id,S.mats[id]===oldN+1&&S.exp.protected[id]);}click('[data-refine="cbar"][data-mode="pure"]');check('purified ward stored',S.exp.flags.ward);
  openCamp('forge');click('[data-project="forge"]');click('[data-craft="pick"]');check('base copper pick crafted',S.gear.pick===1);click('[data-enchant="prospector"]');check('prospector equipped',S.exp.ench.pick==='prospector');const p1=pw();click('[data-enchant="breaker"]');check('breaker changes mining power',pw()>p1*1.4);click('[data-craft="sword"]');click('[data-enchant="ripper"]');check('sword branch equipped',S.gear.sword===0&&S.exp.ench.sword==='ripper');click('[data-enchant="bulwark"]');check('sword branch replaceable',S.exp.ench.sword==='bulwark');click('[data-craft="bow"]');click('[data-enchant="pierce"]');check('ranged branch equipped',S.exp.ench.bow==='pierce');
  openCamp('workshop');click('[data-project="workshop"]');click('[data-utility="bridge"]');click('[data-utility="decoy"]');click('[data-utility="heat"]');click('[data-utility="recorder"]');check('utilities crafted',S.cons.bridge===1&&S.cons.recorder===1);
  openCamp('infirmary');click('[data-project="infirmary"]');closeCamp();CAMP.x=174;CAMP.y=124;K.w=true;for(let i=0;i<120;i++)updateCamp(1/60);K.w=false;check('camp building collision stops movement',CAMP.y>=89);
  const lines=[];const station={who:'Bera',id:'forge'};lines.push(npcLine(station));S.exp.rescues=1;lines.push(npcLine(station));S.boss.brood=1;lines.push(npcLine(station));S.boss.king=1;lines.push(npcLine(station));check('four contextual NPC milestone lines',new Set(lines).size===4);
  S.exp.contract='survey';S.exp.condition='blackout';S.exp.projects.map=1;S.exp.flags.ward=true;S.cons.flare=1;S.exp.seedText='901';startRun(0,0);paused=true;const hp=P.mhp,flare=S.cons.flare;save();const stored=JSON.parse(localStorage.getItem(SKEY));check('blackout grants flares once',flare===6);S.checkpoint=stored.checkpoint;resumeExpedition();check('resume does not grant flares/ward twice',S.cons.flare===flare&&P.mhp===hp);
  paused=false;const beforeP=projs.length;P.aim=0;shoot();check('piercing projectile property',projs.length>beforeP&&projs.at(-1).pierce>=2);paused=true;
  const pe=mkEnemy('crawler',P.x+15,P.y,0);enemies=[pe];S.exp.ench.sword='ripper';P.sw=1;P.swk='sword';hurtEnemy(pe,1,0,0);check('ripper applies bleed',pe.bleed===3);S.exp.ench.sword='frostbrand';hurtEnemy(pe,1,0,0);check('frostbrand applies slow',pe.slow>0);
  const oldHP=P.hp;S.exp.ench.sword='bulwark';P.inv=0;hurtPlayer(10,0,0);check('bulwark reduces swinging damage',Math.abs(oldHP-P.hp-6)<.01);
  paused=false;RUN.x.ability=0;useAbility();check('active ability has cooldown',RUN.x.ability===18);paused=true;
  for(const [a,type] of [[0,'brood'],[1,'king']]){S.exp.condition='calm';S.exp.seedText=String(33+a);startRun(a,ACTS[a].layers.length-1);paused=true;const b=boss;P.x=b.x-100;P.y=b.y;bossAI(b,.1,100,0,100,true);check(type+' entrance',b.st==='roar');b.hp=b.mhp*.45;for(let tick=0;tick<50;tick++)updEnemy(b,.05);check(type+' second phase',b.ph===2);hurtEnemy(b,1e5,0,0);check(type+' route unlock',S.boss[type]&&S.unl[a+1]>=1);if(type==='king'){const delay=RUN.victoryDelay;for(let i=0;i<30;i++)tickUI(.1);check('pause does not advance boss transition',RUN.victoryDelay===delay);}}
  S.exp.seedText='77';S.gear.pick=8;S.up.suit=5;startRun(2,4);paused=true;const b=boss;P.x=b.x-100;P.y=b.y;hurtEnemy(b,1e6,0,0);check('pending ending checkpoint',RUN.pendingEnding&&S.checkpoint.run.pendingEnding);closeStory();S.checkpoint=JSON.parse(localStorage.getItem(SKEY)).checkpoint;resumeExpedition();check('reload reopens final choice',!!dialogue&&RUN.pendingEnding);resolveEnding('sever');check('severing ending persisted',S.exp.ending.includes('sever'));const receipt=JSON.parse(localStorage.getItem(SKEY));applySaveData(receipt);check('results receipt survives reload',S.lastResult&&S.lastResult.won);
  S.exp.flags.seal=true;startRun(2,4);paused=true;hurtEnemy(boss,1e6,0,0);resolveEnding('seal');check('sleeping seal ending persisted',S.exp.ending.includes('seal'));
  S.exp.projects.forge=1;S.exp.ench.pick='breaker';const beforeNG=S.ng;window.confirm=()=>true;enterCamp();showNG();ngSel=['nomad','oath'];click('#b-ngs');check('NG retains camp and build choices',S.ng===beforeNG+1&&S.exp.projects.forge&&S.exp.ench.pick==='breaker'&&S.mods.includes('nomad')&&S.gear.pick===0);showNG();click('#b-ngs');check('second NG cycle retains progression',S.ng===beforeNG+2&&S.exp.ending.length===2);
  const sample=JSON.stringify({format:'deep-below-character',save:S});await new Promise((resolve,reject)=>importSaveFile(new File([sample],'save.json',{type:'application/json'}),err=>err?reject(err):resolve()));check('import/export packet round trip',S.ng===beforeNG+2&&S.exp.projects.forge);
  localStorage.setItem(SKEY,'{invalid');load();check('corrupt save preserved without overwrite',storageLocked&&localStorage.getItem(SKEY)==='{invalid');storageLocked=false;storageWarning='';S=defSave();S.exp.flags.arrival=1;S.exp.flags.briefed=1;
  const setter=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new DOMException('test full','QuotaExceededError')};let saved;try{saved=save()}finally{Storage.prototype.setItem=setter}check('full storage recovers with warning',saved===false&&storageWarning.includes('storage'));
  storageWarning='';state='menu';S=defSave();S.exp.flags.arrival=1;S.exp.flags.briefed=1;S.exp.flags.extraction=1;S.exp.contract='survey';S.exp.seedText='453';startRun(2,0);paused=true;P.mhp=P.hp=100000;P.moil=P.oil=100000;S.up.suit=5;
  for(const type of Object.keys(EB)){const e=mkEnemy(type,P.x+90,P.y+60,0);for(let i=0;i<40;i++)updEnemy(e,.05);check('enemy role update '+type,Number.isFinite(e.x)&&Number.isFinite(e.y)&&Number.isFinite(e.hp));}
  for(let i=0;i<12000;i++){update(.05);updFX(.05);if(P.dead)throw Error('Soak player died');}
  check('10-minute simulation bounded',enemies.length<=200&&parts.length<=700&&projs.length<=180&&items.length<=900&&rocks.length<=80);const reportCounts={enemies:enemies.length,parts:parts.length,projs:projs.length,items:items.length};
  return {passed:rows.length,rows,soak:reportCounts};
 }catch(e){return {error:e.stack,rows}}finally{window.confirm=oldConfirm;storageLocked=false;storageWarning='';state='menu';restoreMode=true;dialogue=null;P=null;RUN=null;S=defSave();if(old){localStorage.setItem(SKEY,old);applySaveData(JSON.parse(old))}else localStorage.removeItem(SKEY);S.exp.seedText='';restoreMode=false;CAMP.active=false;CAMP.menu=null;paused=false;setAct(0);genWorld(4242);showMenu()}
})()
